### ISSUE TITLE
Translation error in country selection

### ISSUE THREAD

**Issue by B-Hartley** [unfoldedcircle/bug-reports#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In country selection list during initial setup.
In American English Language.

GB: United Kingdom

is shown incorrectly as :
GB: Y Deyrnas Unedig

### How to Reproduce

Start from factory reset initial setup.
or access localisation menu.

### Expected behavior

GB: United Kingdom

### System version

UI: 0.29.60 Core:.33.3-beta sys:1.0.5

### What part of the system affected by the problem?

UI

**Comment by Depechie** [comment]
Also Belgium is listed as Belgien.

**Comment by zehnm** [comment]
Quick analysis from the data returned by the core `GET /api/cfg/localization/countries`:
- GB
```json
  {
    "code": "GB",
    "name_cy": "Y Deyrnas Unedig",
    "name_en": "United Kingdom",
    "name_ga": "an Ríocht Aontaithe",
    "name_gd": "An Rìoghachd Aonaichte",
    "name_kw": "Rywvaneth Unys"
  }
```
- BE
```json
  {
    "code": "BE",
    "name_de": "Belgien",
    "name_en": "Belgium",
    "name_fr": "Belgique",
    "name_nl": "België"
  }
```
- Web-Configurator is not affected (and lacks searching by country code)
- Remote-UI seems to take first entry in list, instead of resolving name by code.

@martonborzak could you please check that?

**Comment by martonborzak** [comment]
Yes, the UI was incorrectly taking the correct translations based on country code and not the language code related to the country. Now it's fixed.

**Comment by martonborzak** [comment]
Closing as it has been fixed in previous software update.
