### ISSUE TITLE
[bug] Moving Items in a UI gives big white bix with Chrome Browser

### ISSUE THREAD

**Issue by splattner** [unfoldedcircle/bug-reports#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I move an entity in a UI, my browser shows me a big white box during the movement:

![Screenshot from 2023-10-02 17-49-06](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3875381/3b9cbabe-2572-44d1-80ae-33a442671b26)

The movement of the entity does work, but its a bit annoying and hard to use when half of the screen is blocked by the white box.

I'm using Chrome on a Ubuntu OS. In Firefox it seems to be alright

### How to Reproduce

Got to a ui
Move the position of an entity

### Expected behavior

No white box should apear

### System version

v1.3.3

### What part of the system affected by the problem?

Web Configurator

**Comment by kennymc-c** [comment]
I noticed the same glitch with Chrome on macOS but without the white box. The mouse just sticks to the entity you want to move:

![Bildschirmfoto 2023-10-07 um 21 22 15](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/aef49032-8c22-45eb-b734-521404bc2712)


A similar glitch also appears in Safari in the entities list. All entities that are at the same height position in the entities list as the one you want to move on the remote are moving with it: 


https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/1884962a-5a57-43c9-86e9-d1a29213dd6e

**Comment by splattner** [comment]
with the latest version I still see this error

**Comment by zehnm** [comment]
@splattner I can't reproduce this on Ubuntu 20.04 with Chrome 121. Neither on macOS and Windows 10.
Any more information you could share on how to reproduce this, for example exact OS & Chrome versions and screen resolution?
Do you have any ad-blocker or other JavaScript rewrite addons installed? Try to temporarly disable those to see if that's the cause.

**Comment by splattner** [comment]
Just tested it again with my two Laptops, same behavior

OS: Both Ubuntu 23:10

Chrome: 
* 1 x Version 120.0.6099.224 (Official Build) (64-bit)
* 1 x Version 121.0.6167.139  (Official Build) (64-bit)

Screen Resolution:
* 1 x 1920 x 1680
* 1 x 3440 x 1440 (external Monitor)

No other ones rewriting/blocking JS

Same thing also happens in Incognito with no Extension active.

JS Console doesn't reveal anything
I also did a hard reload/empty cache, but no change.

:thinking:

**Comment by splattner** [comment]
btw, moving a new entity from the right panel into the middle panel works fine. It only occurs when moving around elements in the middle panel, also when moving from the middle to the right panel (to remove).

**Comment by splattner** [comment]
This is how it looks when dragging and moving an item

[Screencast from 2024-02-01 12-24-21.webm](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3875381/6c8f321c-650a-419b-95e4-3d6a37b9eac9)

**Comment by zehnm** [comment]
The related issue #275 is fixed in the next release. It _might_ fix this one as well, but I still couldn't reproduce the big white box.

**Comment by zehnm** [comment]
@splattner could you please test this with the just released 1.6.9 firmware and report back? Another "item move issue" in the user interface page was fixed, hopefully it fixes this one as well :-) Otherwise we have to find a way to reproduce the white box.

**Comment by kennymc-c** [comment]
At least the glitch from my comment on Oct 7, 2023 seems to be fixed

**Comment by splattner** [comment]
yes, the new release has also fixed this. Awesome, thank you
