### ISSUE TITLE
[bug] AppleTV integration asking for PIN when setting up HomePod

### ISSUE THREAD

**Issue by heroclix** [unfoldedcircle/bug-reports#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Setting up Apple TV integration for HomePod fails. Setup wizard asks for a PIN which is not available on HomePod

### How to Reproduce

1. Add Integration
2. Apple TV
3. Select corresponding HomePod
4. Wizzard ask for a PIN ....

### Expected behavior

As with the Apple TV integration in Home Assistant, pairing should be done without the help of PIN for HomePods

### System version

v1.2.1

### What part of the system affected by the problem?

Integration

**Comment by martonborzak** [comment]
The integration is for Apple TVs. HomePods are not supported.
Please open a feature request if you'd like HomePod integration. Thanks.
