### ISSUE TITLE
[bug] Icons no longer displayed in Integrations & docks

### ISSUE THREAD

**Issue by kaandorp** [unfoldedcircle/bug-reports#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to Integrations & docks you see the integrations. If I'm not mistaken I saw logo's there in the previous version. Now I only see puzzle piece icons.

### How to Reproduce

1. Go to Integrations & docks
2. Click on the "+" symbol
3. See the "puzzle piece" icons.

### Expected behavior

I expect to see the icons for the corresponding integration.

### System version

1.3.3.

### What part of the system affected by the problem?

Web Configurator

### Additional context

![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/8036227/bc6954c2-e9db-4cb8-9f2a-fc2d915151c0)

**Comment by zehnm** [comment]
See 1.3.3 release notes:
```
Integration icons have been removed to avoid confusion of nominative fair trademark use.
You’ll be able to upload your own after a future update.
```

Release notes are shown on the device before update, in the [community forum](https://unfolded.community/t/firmware-release-1-3-3/504) and in our [Discord channel](http://unfolded.chat/).

Power users can already use the REST Core-API to set custom icons for the integration drivers and configured integrations:

Driver:
```shell
curl --request PATCH 'http://$IP/api/intg/drivers/$DRIVER_ID' \
--header 'Content-Type: application/json' \
--data '{"icon": "custom:$MY_ICON"}' \
-u webconfigurator:$PIN
```

- `$IP` is the remote's IP address or hostname
- `$DRIVER_ID` can be retrieved with `GET /api/intg/drivers`
- `$MY_ICON` is an uploaded custom icon
- `$PIN` is the web-configurator pin

Configured integration:
```shell
curl --request PATCH 'http://$IP/api/intg/instances/$INTEGRATION_ID' \
--header 'Content-Type: application/json' \
--data '{"icon": "custom:$MY_ICON"}' \
-u webconfigurator:$PIN
```

$INTEGRATION_ID is visible in the web-configurator when editing an integration (`Id` field) or with `GET /api/intg/instances`

**Comment by zehnm** [comment]
Next release will have web-configurator support to choose a custom icon:
<img width="414" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/f4f3a915-5717-4755-8c36-5586e5c17e7a">

**Comment by zehnm** [comment]
Editing icons is part of 1.4.3
