### ISSUE TITLE
No option to disable sleep timeout

### ISSUE THREAD

**Issue by Laess3r** [unfoldedcircle/bug-reports#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hey there!
Without the option to disable sleep timeout, it is hard to use the device as a TV remote.

You can't just pick the remote up from the sofa and pause playback (eg. on Apple TV) because the remote is not connected any more. Coming back to the TV after >5min also requires me to wait for WiFi connection to continue playback.

I think we need an option to disable sleep at all. 

Maybe it would be enough to prevent sleep as long as media is playing. 

Best,
Stefan

### How to Reproduce

1. Click on top right on remote
2. Go to settings
3. Go to power saving
4. Sleep timeout can only be changed between 10 seconds and 5 minutes.

### Expected behavior

The remote should not go to sleep as long as media is playing.

### What part of the system affected by the problem?

Core

**Comment by kennymc-c** [comment]
There is a [roadmap](https://www.unfoldedcircle.com/software-roadmap) item planned for September which seems to prevent this:
- Option for activity to prevent remote to enter deep sleep mode

**Comment by Laess3r** [comment]
Okay, thank you! So I guess I'll wait a few months until my Harmony really can be retired. 

@martonborzak maybe the first checkbox should also contain " i checked the roadmap" 😅

**Comment by Laess3r** [comment]
Thank you for extending the timeout to 30min in version 1.1.1! That helps already a lot
