### ISSUE TITLE
[bug] Web UI alignement on start page not correct / overlapping

### ISSUE THREAD

**Issue by F4Ck0R** [unfoldedcircle/bug-reports#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Web UI alignement seems to be off on the default screen:

![Screenshot 2023-10-08 130228](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/111465037/d84f1d3f-4c3d-4105-b275-58e316e7decc)

### How to Reproduce

1. Open web UI in Microsoft Edge Chromium
2. Login

### Expected behavior

Remote should be centered and marked areas should not overlap.

### System version

RemoteTwo v1.3.3

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
@martonborzak probably best if you track this issue / include it in the redesign.
It's the same behaviour with Chrome on macOS.

**Comment by martonborzak** [comment]
The menu always overlaps the content below. That is not a bug. 
I'd also argue that the text can overlap the remote as it's just a decorative element.
