### ISSUE TITLE
Cannot add AndroidTV integration

### ISSUE THREAD

**Issue by karies** [unfoldedcircle/bug-reports#119]
Hi,

Firmware 1.3.3, trying to connect to a Google Chromecast 2. When starting the integration it finds the device ("Wohnzimmer TV") and the Chromecast displays a 6 character code ("Enter this code in our Remote Two" - yay!) but then the remote times out. It never displays a box to enter the code.

I have reset the dock, no luck.

Something I'm doing wrong?

[Some logs](https://github.com/unfoldedcircle/integration-home-assistant/files/12834885/UCR2_logs_2023-10-06-all.txt) - I hope they help.

Cheers, Axel

**Comment by zehnm** [comment]
Wrong repo, this is for the Home Assistant integration. Moving to https://github.com/unfoldedcircle/feature-and-bug-tracker

**Comment by karies** [comment]
Works like a charm in firmware 1.4.8 through the web interface.
