### ISSUE TITLE
[feature request] Making the "Activity off" sequence to be available to be called as a command

### ISSUE THREAD

**Issue by KarlKiel** [unfoldedcircle/bug-reports#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At the moment only the start of activities can be triggered as a command within macros, on- or off-sequences for activities or for button commands.
It would be great to similarily give the chance to "stop" activities in a the same way that the defined "off sequence" for the activity is being called (and the activity will go into "off" state accordingly).
There are several different use cases where this might be very powerful to handle a large number of open activities and it also can provide solutions to handle different activities that leverage an overlapping set of entities and/or will not be able to be active at the same time.

**Comment by zehnm** [comment]
Interesting that nobody noticed that yet, it should have been there 😄 It's back in the next release:
<img width="766" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/7f818e38-c216-43bf-ba07-ed70ab7ac1fc">

**Comment by zehnm** [comment]
Closing: part of 1.4.3
