### ISSUE TITLE
Support IR Remote Controls that use Toggle Bit

### ISSUE THREAD

**Issue by KarlKiel** [unfoldedcircle/bug-reports#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A lot of IR controls have implemented 2 sets of IR Codes and toggle between the those 2 sets at every press of a button.
This functtionality is also called "Toggle Bit" and is also for example part of the official definition of the very commonly used RC-5 protocol. (e.g. https://de.wikipedia.org/wiki/RC-5)
The idea is to prevent that the same code is interpreted more than once from the end device.
Unfortunately Remote2 (and Remote 1 also..) are not supporting Toggle Bit today - therefore a device that uses Toggle Bit will only interpret one press of a button and ignore all following presses of that same button before any button press of aother button has been interpreted.
Here an example for such a toggle bit that is sent at two following presses (RC5, Page 7, Command 16:)
Standard:
0000 0073 000B 0000 0020 0020 **0040** 0020 **0020** 0020 0020 0040 0020 0020 0020 0020 0040 0040 0040 0020 0020 0020 0020 0020 0020 09B7 
"Toggled":
0000 0073 000B 0000 0020 0020 **0020** 0020 **0040** 0020 0020 0040 0020 0020 0020 0020 0040 0040 0040 0020 0020 0020 0020 0020 0020 09B7
Would be great to support the toggle bit behaviour to support a lot more devices with smooth control.

**Comment by zehnm** [comment]
Toggle bits for RC-5 and RC-6 are in our backlog. Sometime after the internal IR blaster functionality and native IR-repeat is done.

We will start with learned codes, where it's easy to process the toggle bit, then check about the existing PRONTO codes.

**Comment by zehnm** [comment]
The initial rewrite of the RC5, RC5X and RC6 toggle-bit handling has just been released in the BETA group as a preview feature. It should be available as a public update soon (but still as preview-feature after more testing has been done).

**Comment by zehnm** [comment]
Status update: another BETA version has been released and we are getting close to a public release.
- New toggle logic is active by default and no longer a preview feature.
- RC-6 has been verified with an HP MCE remote & USB receiver
- Self learned RC-5, RC-5x, RC-6 and RC-MM 32bit codes are automatically toggled, no matter if the learned code has the toggle bit set or not.
- PRONTO codes can be toggled with a `|` devider: `<CODE1> | <CODE2>`
  Example with the codes given in this issue:
  `0000 0073 000B 0000 0020 0020 0040 0020 0020 0020 0020 0040 0020 0020 0020 0020 0040 0040 0040 0020 0020 0020 0020 0020 0020 09B7 | 0000 0073 000B 0000 0020 0020 0020 0020 0040 0020 0020 0040 0020 0020 0020 0020 0040 0040 0040 0020 0020 0020 0020 0020 0020 09B7`

**Comment by zehnm** [comment]
Fixed in 1.6.0
