### ISSUE TITLE
[bug] Incomplete German translation despite approved strings on Crowdin

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was hoping that the recent 1.4.2 firmware update will finally include a complete German translation. On Crowdin all strings have been translated for a few month now and have also recently been approved. But they don't seem to be integrated in the firmware yet.

### How to Reproduce

1. Change language to German
2. Many things in the UI and web configurator are still in English, e.g the Back button and some settings

### Expected behavior

Everything should be translated to German

### System version

1.4.2

### What part of the system affected by the problem?

Overall system

### Additional context

It would be nice if new string notifications for translators in the Crowdin project settings could be turned on

**Comment by zehnm** [comment]
Approved strings are not automatically included in the software, there's another integration process involved, which requires human confirmation. It's in the queue!

**Comment by zehnm** [comment]
Included in 1.4.3
