### ISSUE TITLE
[bug] Self configured MCE buttons are working only once

### ISSUE THREAD

**Issue by fischy667** [unfoldedcircle/bug-reports#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some self configured MCE buttons are only working the first time if you press them several times.

- Red function
- Green function
- Blue function
- Yellow function
- Guide
- Channel up/down
- Volume up/down
- Cursor up/down

maybe more.

An IR command is send every time, my IR receiver has an indicator for that, but the called action is not executed.

When another button is pressed, the affected buttons are working again one time.
With an original remote control, the called function is executed several times directly one after the other.

### How to Reproduce

1. Setup a Remote and teach the remote a MCE button e.g. Channel Up
1. Press the learned button multiple times
2. The called function is executed only ones

### Expected behavior

The called function is executed several times directly one after the other.

### System version

Remote v1.4.2; Dock v0.9.2

### What part of the system affected by the problem?

Core

### Additional context

Could be related to #126. I found information that MCE remotes use toggle bits.

**Comment by fischy667** [comment]
I did not want to close this. Sorry

**Comment by zehnm** [comment]
This is part of #126: supporting toggle bit for RC-5 and RC-6 protocol.

**Comment by zehnm** [comment]
The initial rewrite of the RC5, RC5X and RC6 toggle-bit handling has just been released in the BETA group as a preview feature. It should be available as a public update soon (but still as preview-feature after more testing has been done).

Self learned codes are supported as well. These are with prefix: `1;` (RC5), `23;` (RC5X), `2;` (RC6).

**Comment by zehnm** [comment]
Status update: another BETA version has been released and we are getting close to a public release.
- New toggle logic is active by default and no longer a preview feature.
- RC-6 has been verified with an HP MCE remote & USB receiver
- Self learned RC-5, RC-5x, RC-6 and RC-MM 32bit codes are automatically toggled, no matter if the learned code has the toggle bit set or not.

**Comment by zehnm** [comment]
Fixed in 1.6.0
