### ISSUE TITLE
Missing or invalid media_player.shuffle parameter: shuffle

### ISSUE THREAD

**Issue by GekoCH** [unfoldedcircle/bug-reports#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I tried to add a shuffle button to the remote.
However when I take the command shuffle form a Media player entity I get this error:
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3285638/1c5bdcbc-34ea-4570-94ee-7d123a965274)

### How to Reproduce

Go to Activities
Select an Icon
Set the command to Shuffle
error appears

### Expected behavior

Icon does not work afterwards.
So if I press the Icon it should send the command Shuffle

**Comment by zehnm** [comment]
This is fixed and will be included in the next release.

**Comment by zehnm** [comment]
Closing: fixed in release 1.4.5
