### ISSUE TITLE
[bug] DIGIT_3 and DIGIT_5 from Sony generic TV data sets are not working

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I noticed that the DIGIT_3 and DIGIT_5 commands that are included in both Sony Generic TV 1 and 2 IR data sets are not working. All other Digits are working correctly on my Sony XE9005. I had to manually add the commands by learning them from the original remote to be able to switch to the specified channel number.

### How to Reproduce

1. Go to to Remotes and click on +
2. Search for Sony in data sets
3. Select either Generic TV 1 or 2
4. Search for the DIGIT_3 and DIGIT_5 commands
5. Click on the commands to test it

### Expected behavior

You should be be able to use the DIGIT_3 and DIGIT_5 commands to switch to the specified channel number

### System version

1.4.3

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Indeed, 3 & 5 don't work. Will be fixed. In the meantime these are the working codes:
- DIGIT_3: `4;0x410;12;0`
- DIGIT_5: `4;0x210;12;0`

**Comment by zehnm** [comment]
This is fixed in next release.

**Comment by zehnm** [comment]
Included in v1.5.2
Existing remote-entities are not automatically updated. Only newly created remote-entities will get the updated codes. For existing entities the above codes can be used to override the keys.
