### ISSUE TITLE
[bug] Remote UI crashes when removing entity from group

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I noticed a bug that crashes/restarts the remote UI App when you try to delete an entity from a group through the remote ui.

https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/df83b091-2f14-4d6e-815a-9e1aa5da7eab

### How to Reproduce

1. Add entitiy to group
2. Add group to a page
3. Open the group on the remote
4. Long press on the entity and choose remove

### Expected behavior

The entity should be removed and the remote should not crash

### System version

1.4.3

### What part of the system affected by the problem?

UI

### Additional context

Core & Remote UI app debug logs: [UCR2_logs_2023-10-23-2.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13074686/UCR2_logs_2023-10-23-2.txt)

**Comment by martonborzak** [comment]
Fixed in the next update.

**Comment by zehnm** [comment]
Closing: fixed in release 1.4.5
