### ISSUE TITLE
[bug] Buttons of the integrated MCE remotes are send twice

### ISSUE THREAD

**Issue by fischy667** [unfoldedcircle/bug-reports#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the fix of #89 the commands of the MCE are useable, but every command of certain buttons are send twice.

- Red function
- Green function
- Blue function
- Yellow function
- Guide
- Channel up/down
- Volume up/down
- Cursor up/down

maybe more.

### How to Reproduce

Add a Microsoft MCE remote and send one of the buttons to a PC.

### Expected behavior

The command is executed once.

### System version

Remote v1.4.3; Dock 0.9.2

### What part of the system affected by the problem?

Core

**Comment by leoschweizer** [comment]
I have observed the same with my Marantz AVR Volume up / down and mute (the latter is basically unusable due to this, since it will always mute and immediately unmute again)

**Comment by zehnm** [comment]
This is part of #126: supporting toggle bit for RC-5 and RC-6 protocol.

Unfortunately, #89 turned out to be more of a hack and not a proper solution. Proper toggle bit support is the only way.

**Comment by zehnm** [comment]
I've started working on proper toggle support for the integrated codesets. An MCE RC-6 remote & USB receiver is on the way to test it and make sure it works! Unfortunately delivery will take 2-3 weeks. Backup plan is to re-purpose one of my Intel NUCs, since they have integrated IR...
I could also release it sooner as a preview feature, if someone is willing to help out testing.

**Comment by fischy667** [comment]
Sure, I would be happy to support you with testing.

**Comment by zehnm** [comment]
The initial rewrite of the RC5, RC5X and RC6 toggle-bit handling has just been released in the BETA group as a preview feature. It should be available as a public update soon (but still as preview-feature after more testing has been done).

**Comment by zehnm** [comment]
Status update: just received the HP Windows Media Center MCE IR RC6 remote & USB receiver and will start testing soon.

**Comment by zehnm** [comment]
Status update: another BETA version has been released and we are getting close to a public release.
- New toggle logic is active by default and no longer a preview feature.
- RC-6 has been verified with an HP MCE remote & USB receiver
- Self learned RC-5, RC-5x, RC-6 and RC-MM 32bit codes are automatically toggled, no matter if the learned code has the toggle bit set or not.
- Included MCE codesets have been verified with an Intel NUC and the HP MCE receiver

**Comment by zehnm** [comment]
Fixed in 1.6.0
