### ISSUE TITLE
[bug] Incomplete and wrong list of apps in Android TV integration

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Android TV integrations only seems to show a fixed list of apps that have nothing to do with the actually installed apps on the device. I even see apps like HBO Max that are not available in my Play Store region. When I try to open one of the not installed apps I get redirected back to the main menu of the remote or the website of the service gets opened in the integrated browser.
In comparison the Apple TV integration only shows all installed apps.

### How to Reproduce

1. Start the Android TV integration
2. Tap on the apps button
3. Tap on one of the apps

### Expected behavior

All and only apps that are installed on the device should show up in the apps menu

### System version

1.4.3

### What part of the system affected by the problem?

Integration

**Comment by zehnm** [comment]
This is correct: the list of apps is pre-defined list of common apps. At the moment it's not possible to retrieve a list of installed applications for Android TV with the [androidtvremote2](https://github.com/tronikos/androidtvremote2) communication library we are using.

User editing of the pre-defined apps is in the backlog, also switching physical input sources. See https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/128#issuecomment-1768654779

**Comment by splattner** [comment]
I think the problem is also, that the Android TV Remote Protocol only allows to use Deeplinks for opening apps and they have to be supported by the App. You cannot open an arbitrary app by its name. Not all apps Supports them. E.g. Quickline TV (a local Swiss TV Provider) don't have a Deeplink set, so I cannot open it)
