### ISSUE TITLE
[bug] activity/remote title disappears when editing UI

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since one of the last updates I noticed that the title/headline of some activities and ir remotes have disappeared. After a reboot they are visible again. I am able to reproduce this when editing the UI of the activity/ir remote.

https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/2a0140ca-3ebc-4d3f-a9a0-b2f36ffae365

### How to Reproduce

1. Add ir remote or activity to a page
2. Add or change something in the ui editor of the added activity/remote

### Expected behavior

The title/headline should not disappear

### System version

1.4.3

### What part of the system affected by the problem?

UI

### Additional context

Core & UI debug logs: 
[UCR2_logs_2023-10-28.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13195711/UCR2_logs_2023-10-28.txt)

**Comment by martonborzak** [comment]
This is fixed in the upcoming update.

**Comment by zehnm** [comment]
Closing: fixed in release 1.4.5
