### ISSUE TITLE
[bug] activity hardware button mappings stop working

### ISSUE THREAD

**Issue by leoschweizer** [unfoldedcircle/bug-reports#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

See "how to reproduce"; hardware button functions will stop doing anything inside an activity after using the entities menu in the same activity.

### How to Reproduce

1. Create an activity with multiple entities
2. Map some actions of an entity to hardware buttons on the remote
3. Start the activity
4. Go to the entities menu in the activity, select one of the entities and run an entity-specific commands
5. Close the entities menu back to the activity screen
6. Hardware buttons will no longer do anything

### Expected behavior

Hardware buttons should still be mapped properly after using the entities menu.

### System version

v1.4.3

### What part of the system affected by the problem?

UI, Core, Overall system

**Comment by martonborzak** [comment]
This will be fixed in the upcoming update.

**Comment by zehnm** [comment]
Closing: fixed in release 1.4.5
