### ISSUE TITLE
Remote drains within hours whilst not in use

### ISSUE THREAD

**Issue by Dicky-12** [unfoldedcircle/bug-reports#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a full charge I only manage to get a few hours of use, I leave the remote on overnight and it drains completely by the next day without use.

I have x2 remotes and they’re both configured to minimal power saving settings. One lasts for 2 days on a full charge, the other is described as above.

### How to Reproduce

Fully charge the remote
Leave the remote overnight (9hrs)
Next day battery is fully depleted.

### Expected behavior

At least a few days use before requiring another charge. Depending on use.

### System version

1.4.3

### What part of the system affected by the problem?

Overall system

**Comment by kennymc-c** [comment]
Have you checked if there is any activity running that prevents the remote from going into sleep mode?

**Comment by Dicky-12** [comment]
Thanks. I noticed the ‘Sleep Mode’ option in the ‘Activity’ was set to on. I thought this was related to not allowing the remote go into sleep mode when configuring an activity via the config screen. I now understand this stops the remote going into sleep mode when the activity is selected via the remote.
