### ISSUE TITLE
Select source not working

### ISSUE THREAD

**Issue by bartberden** [unfoldedcircle/bug-reports#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select source and select sound mode are not working for me. I’m unable to pass/save any value given in the activity page editor. Both hass and appletv integration dont work.

### How to Reproduce
On Safari on MacOS Ventura,
Go to activities, go to page editor and add an icon or text. Select select souce as action and type something in the inputfield. It says saving ok, but actually is empty

### Expected behavior

Id expect a dropdown with items from source_list, or typing in a source.

### System version

V1.1.0

**Comment by splattner** [comment]
I can confirm this, same here

**Comment by martonborzak** [comment]
This has been fixed in a previous software update.
If no sources are available to select from a list an input field is shown as alternative.
