### ISSUE TITLE
[bug] Dock firmware version doesn't update FW version information on web configurator UI

### ISSUE THREAD

**Issue by GitPetri** [unfoldedcircle/bug-reports#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

One of the two docks I received came with FW 0.9.0. Running the firmware update showed success but the FW version data in the web configurator doesn't get updated.
FW information via remote itself shows FW 0.9.2 for the dock in question

### How to Reproduce

1. Open web configurator
2. Open dock settings
3. Update the firmware to available 0.9.2
4. After the update web configurator UI shows 'Your software is up to date' but FW version is shown as 0.9.0
5. FW version information on the remote itself shows FW 0.9.2 for the dock in question
<img width="392" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/33396519/4d4f3dc0-80ad-43f1-b8f1-63fa39ce78da">

### Expected behavior

Web configurator UI shows correct FW version for the dock

### System version

0.9.2 / 0.9.0

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
This is fixed in the next release

**Comment by zehnm** [comment]
Fixed in the just released version 1.6.4
