### ISSUE TITLE
Wrong shown version in web configurator

### ISSUE THREAD

**Issue by zucki** [unfoldedcircle/bug-reports#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The shown version in the lower left corner of the web-configurator does not fit to the version shown in the remote menu.
![image](https://github.com/unfoldedcircle/bug-reports/assets/4253035/b382d022-2e0e-4973-84cd-cf329bc7ae77)
Installed version is 1.1.1

### How to Reproduce

1. open web-configurator
2. check version shown in the lower left corner

### Expected behavior

shown version in web-configurator and on the remote should be the same

### System version

v1.1.1

**Comment by martonborzak** [comment]
I assume after refresh this works too?

**Comment by zucki** [comment]
Yes 👍 
Maybe you can add a hint to the release-notes or to the Discord "firmware-updates" channel to do a hard-refresh after installing a new update
Thanks again
