### ISSUE TITLE
[bug] remote two will not pair with dock

### ISSUE THREAD

**Issue by ianhyzy** [unfoldedcircle/bug-reports#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Remote Two won't pair with the dock. 

### How to Reproduce

When pairing wirelessly, it will show as avaiable and ask for the wifi password, but throw a timeout error after continuing. When plugged in with Ethernet, the dock is never found.

### Expected behavior

The dock is found and connects. 

### What part of the system affected by the problem?

Overall system

### Additional context

I have a Unifi system

**Comment by zehnm** [comment]
Discovering and connecting to the dock requires mDNS to work properly in the WiFi network.

After pairing and the timeout: do you see the dock connected in your access point / router?

Please make sure that your access point doesn't block mDNS. When the dock is connected with ethernet, it needs to be in the same network and not in another subnet.

If you use different network segments or disabled mDNS, then the dock needs to be configured manually with its IP address:

1. Open and log-in to Web-Configurator
2. Go to Integrations & Docks
3. Click + in the Dock section
4. Select "Manual setup"
5. Give it a friendly name and set the IP address

The IP should be assigned statically in your DHCP server.

**Comment by ianhyzy** [comment]
mDNS is on, even plugging the dock in via ethernet it doesn't show up in the unifi control center. I [can't access](https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/183#issuecomment-1803764749) the web configurator

**Comment by ianhyzy** [comment]
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/696202dc-e711-4473-a20d-95f31cd5fdf6)
took a screenshot of my network settings

**Comment by ianhyzy** [comment]
I tried this again after un-checking BSS transitions but it still won't take on wifi. I get a spinning X animation and then it stays at the dock config screen (Showing the dock's bluetooth ID where you put in the wifi info).

**Comment by ianhyzy** [comment]
It looks like Unifi can see the dock (Unifi thinks it's an IKEA Tradfri hub?) but it doesn't have an IP assigned.
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/a51ae57a-6b70-4636-839e-ba0d6db885a9)

**Comment by ianhyzy** [comment]
I tried hard wiring it and setting up manually with the IP in the configurator but get the same error:
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/cd9efbd7-14b8-4b9e-b7c2-f28e047dc9c0)
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/b88ed6d3-aa17-4837-a921-6b5312b06e8d)

**Comment by ianhyzy** [comment]
https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/183#issuecomment-1817958754

**Comment by ianhyzy** [comment]
I think this was an issue with the dock not getting enough power and the remote was going to sleep even though it was charging
