### ISSUE TITLE
[bug] Configurator does not load

### ISSUE THREAD

**Issue by ianhyzy** [unfoldedcircle/bug-reports#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The web configurator does not load with the shown address, the IP address, or http://IP_address/configurator 

### How to Reproduce

Attempt to connect to the web configurator on another device 

### Expected behavior

The web configurator loads 

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
We need a bit more information to figure out what the issue is.

What do you mean exactly with "does not load"?
- You can't open the page or get an error message?
- Login doesn't work?

Some general points:
- Please make sure that the remote doesn't sleep. It's best to put it in the dock while using the web-configurator.
- The other devices need to be on the same network.
- Certain access points or hotspots prevent communication between WiFi devices and only allow WAN access.

**Comment by ianhyzy** [comment]
I get the Chrome error message of a timeout / no connection at all. The remote is awake or in dock when trying to connect. All of the devices are on the same network and can communicate with each other, I have other smart home devices on a mix of 5ghz/2.4/wired that work.

**Comment by ianhyzy** [comment]
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/5bc0545a-86de-464a-bd6d-f7517edce0dd)
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/34c42828-36aa-40e0-b1f8-3142089bf85b)
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3400872/bc2b0507-40ac-4faa-9430-a18340ea31ab)

**Comment by ianhyzy** [comment]
Un-checking BSS Transition in my router settings fixed this 

edit: temporarily fixed it, the configurator is inaccessible again and I didn't change anything.

**Comment by Marco4223** [comment]
Hi @ianhyzy ,
please keep in mind that the remote have to be online. Did this also happen when the remote is in the dock?

**Comment by ianhyzy** [comment]
yes, it's in the dock when I'm trying.

**Comment by ianhyzy** [comment]
I had the dock plugged in via ethernet to a switch on my unfi network. Plugging it into the dream machine directly made both the web configurator and dock finding work correctly. I have a ton of other smart home devices on that switch that works fine though .

**Comment by ianhyzy** [comment]
I think this was an issue with the dock not getting enough power and the remote was going to sleep even though it was charging, and issues with how the remote handles 2.4/5 mixed networks
