### ISSUE TITLE
Dock does not update from version 0.9.0 to 0.9.2

### ISSUE THREAD

**Issue by snapjack** [unfoldedcircle/bug-reports#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use the remote two firmware version 1.4.5 configured in german. I was able to connect the dock. When I go to the dock under "Integrations & Docks" in the web interface, I can see the dock. It has firmware 0.9.0. I click the dock, it shows "New firmware available", I click "Update", a empty popup opens and I get the error:

Komponentenfehler: 5 Request failed with status code 503

In the log files I get errors like so:
2023-11-09 13:42:20.562084 +00:00	core	NOTICE	Added standby inhibitor: Dock firmware update: custom-eaf840
2023-11-09 13:42:16.584836 +00:00	core	ERROR	Error encountered while processing the incoming HTTP request: ServiceUnavailable("Unsupported dock")

### How to Reproduce

1. Open Web Configurator
2. Go to "Integrations & Docks"
3. Open the Dock, it should have firmware 0.9.0
4. Firmware 0.9.2 is available
5. Press "Update"
6. You get the error message "Komponentenfehler: 5 Request failed with status code 503"

### Expected behavior

No error and firmware updates ;-)

### System version

remote 1.4.5, dock 0.9.0

### What part of the system affected by the problem?

Overall system

**Comment by zehnm** [comment]
Thanks for providing the log entries!
The `Unsupported dock` message is a good hint. What do you see as `Service name` when you edit the dock in the web-configurator? Does it start with `UC-Dock...` as in the following image?

<img width="546" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/d0503de1-c9d4-47b4-bfc6-4eb6154eb0df">

**Comment by snapjack** [comment]
Here is my view:
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/30823524/1ed26b34-4461-4707-9d8e-ab9375cd3f7c)

**Comment by snapjack** [comment]
I was not able to connect the dock via scan. I had to add it manually using the IP of the dock. It's connected via LAN cable. I use a FritzBox 7530 and a Fritz Repeater 3000 and a Fritz Repeater 6000. The remote is connected via WLAN to the repeater 6000.

**Comment by zehnm** [comment]
Found it: a wrong check slipped in from the Simulator!
All custom configured docks are flagged as simulated docks... 🙈
Which then prevents the firmware update being uploaded.

Will be fixed in the next update.

Manual update:
1. Download the firmware ZIP file below and unpack it
2. Determine the IP address of your dock
3. Use the following curl command to update your dock:
```shell
curl  -F "file=@UCD2-firmware_v0.9.2.bin.signed" http://${DOCK_IP}/update
```

[UCD2-firmware_v0.9.2.bin.signed.zip](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13309323/UCD2-firmware_v0.9.2.bin.signed.zip)

**Comment by snapjack** [comment]
Has worked:

Update: OK!

**Comment by zehnm** [comment]
The next release has improved error handling in the web-configurator for dock firmware updates.

**Comment by zehnm** [comment]
Closing: release 1.6.4 has improved error handling for dock updates
