### ISSUE TITLE
Unable to set up home assistant integration

### ISSUE THREAD

**Issue by twodice** [unfoldedcircle/bug-reports#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm attempting to set up the home assistant integration on a brand new remote. I have the correct url for my server (`wss://home.domain.com/api/websocket`) that works via the command line on my computer. When I attempt to set it up in the remote's web UI I get the error:
`Error on load: AxiosError: Request failed with status code 500` at the bottom of the page and no suggested entities to connect with. 

### How to Reproduce

1. Attempt to set up the home assistant integration from the web UI
2. Enter the URL and credentials
3. Hit next
4. See the error and no entities

### Expected behavior

I'd expect to see no error and a list of entities.

### System version

v1.1.1

### What part of the system affected by the problem?

Web Configurator, Integration

**Comment by twodice** [comment]
From the logs, the error appears to be:
```
2023-09-05 21:19:52.451406 +00:00	intg-homeassistant	INFO	[2023-09-05T21:19:52Z WARN  uc_intg_hass::controller::handler::ha_connection] Could not connect to wss://home.domain.com/api/websocket: SendRequest(TunnelNotSupported)

```

**Comment by Laess3r** [comment]
Your example url seems to be missing the home assistant port. For my installation it was :8123.

**Comment by twodice** [comment]
The port doesn't seem to make a difference - it's hosted on port 443 and I tried both:
```
wss://home.domain.com:443/api/websocket
wss://home.domain.com/api/websocket
```

443 should be implied by `wss://` but manually specifying it doesn't seem to help.

**Comment by nikos1988** [comment]
> Are you using a self-signed certificate? That doesn't work at the moment, uploading custom certificates is still in the backlog. Can you connect with `ws://`?

I can't find self-signed certificate support in the software roadmap. Is it still planned?
