### ISSUE TITLE
[feature request] LG webOS integration

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I would like to integrate my LG TV with webOS into Remote Two and do not want to run a separate service for this like Home Assistant.

**Comment by janosikcs** [comment]
Hi ..


LG integration Home Assistant is not work. Help me

**Comment by ascl00** [comment]
It seems like there are a few libraries across multiple languages that talk to webos, so it shouldn't be too hard (hopefully) to create this integration:
https://github.com/kziemianek/lg-webos-client (rust)
https://github.com/kaperys/go-webos (go)
https://github.com/TheRealLink/pylgtv (python)

None are super up to date, but might be enough.

**Comment by kennymc-c** [comment]
Thanks to @albaintor there is now an external integration for LG WebOS TVs: https://github.com/albaintor/integration-lgtv
