### ISSUE TITLE
Icons are lost on Macros that are added to a main page in the profile

### ISSUE THREAD

**Issue by apgr** [unfoldedcircle/bug-reports#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have created a bunch of macros to control my HUE lights. I have created a main page in the profile for lights (in addition to one for activities and one for devices).

I have have set icons for the various dimming scenes.
<img width="336" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3209742/8a37ec4c-b6fd-409e-8beb-b07a80a1f0ae">

However after a while they disappear on the remote itself.
![IMG_7557](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3209742/92f9d04b-bcab-4252-93bd-abf0ea985ce5)

If I go and reinstall each icon by hand then they come back for a while.

### How to Reproduce

1. Add macros to a page in the profile and select a new ICON for the macro.
2. Just wait a while and they stop appearing in the remote, even though they still appear in the web configurator.

### Expected behavior

Icons don't disappear 

### What part of the system affected by the problem?

UI

**Comment by zehnm** [comment]
@apgr what do you mean with "wait a while"? More like minutes/hours or days?

Either way, this should not happen. I've setup a test profile with a page containing six macros with different icons to track it down.

**Comment by apgr** [comment]
@zehnm - Sorry for the ambiguity here.  I have done it three times now and certainly by the next day, they have reset back to the default icons.  So I think we are talking hours.

FWIW I have also added use of the same macros to some of my activities, and here the (same icons) stay.  I am using the lights icons from the default set as you can see above.

**Comment by zehnm** [comment]
And I could reproduce it: it's a UI issue, the macro data is stored correctly, and as you already mentioned, showed correctly in the web-configurator.

**Comment by zehnm** [comment]
This will be fixed in the next release.

**Comment by zehnm** [comment]
Included in BETA release group and soon available.

**Comment by zehnm** [comment]
Fixed in v1.5.2

**Comment by apgr** [comment]
Thank you!
