### ISSUE TITLE
Custom IR Codes stay in internal DB after deletion

### ISSUE THREAD

**Issue by Marco4223** [unfoldedcircle/bug-reports#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After I deleted my old IR Codes set the export still contains that set. So when I try to setup one new with the same name I got the information that there still one exist.

### How to Reproduce

Go to remotes and delete one of the existing remote sets. Try to create a blank one with the same name.
To check if they still exist go to settings and export the custom IR codes

### Expected behavior

If I delete a set it should be permanently deleted.

### System version

1.4.8

**Comment by kennymc-c** [comment]
By deleting the remote entity you are not deleting the actual code set in the DB.
Currently you have to delete custom code sets via the API as described in #4 .

**Comment by Marco4223** [comment]
Thx for letting em know. Then I can close this one.
