### ISSUE TITLE
Learned or copy pasted commands do not work (from remote)

### ISSUE THREAD

**Issue by DePeer** [unfoldedcircle/bug-reports#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Codes learned to or copy pasted in the web configurator work when using the TEST button in the configurator. However when these commands are issued from the remote nothing happens. This is with all the codes i put in so far. The codes that were in the existing database do work from remote. So far found one more person in Discord with this strange issue.

### How to Reproduce

1. learn code to remote
2. hit test button
3. see confirmation on controlled device that it is a working code
4. issue learned command from remote 2
5. nothing happens

### Expected behavior

learned codes issued from remote do work as test also worked.

### System version

1.4.8

### What part of the system affected by the problem?

Overall system

**Comment by DePeer** [comment]
edit, commands send from the dock work so only the ir extenders do not work when command is sent from remote but do work when sent from configurator test.

**Comment by zehnm** [comment]
@DePeer could you please post a learned IR command that doesn't work?

I assume it's an RC-5 or RC-6 code, then it's the toggle bit issue #126. The command works just once, then another command has to be sent, that it works again once more.

**Comment by DePeer** [comment]
> @DePeer could you please post a learned IR command that doesn't work?
> 
> I assume it's an RC-5 or RC-6 code, then it's the toggle bit issue #126. The command works just once, then another command has to be sent, that it works again once more.

Hi, this one has nothing to do with the codes, it simply is the fact that when command is sent from remote it is not send out through the IR extender but only through the dock IR. When sending the code through webconfigurator 'test' it does send also through IR extension cable. 
Had to 'break' out equipment from cabinet to make sure. So to summarize; when testing from configurator is also goes through extender, when same command send from remote it only emits from dock.

**Comment by zehnm** [comment]
I can't reproduce this and need some more information:

- Which output port did you select when testing the learned IR code?
  I assume this is in the following dialog (where I used Ext 2), correct?

<img width="938" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/6e490a11-cf8a-4a06-8c4b-e4f23703dd50">

- Did you select the same IR output port in the remote-entity configuration?

<img width="541" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/8b0ce37d-63dd-4781-9fe0-0b3cf87f4a99">

- Please post a learned code, just to make sure it's not a protocol issue.

**Comment by DePeer** [comment]
Hi, Either I use default (which is all) or I select ext 1 (which is where extender is attached). When I hit the test button all goes well, when I push same button on remote only the dock emits IR and not ext 1. In case I choose only ext 1 nothing happens at all when using remote.
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/122922920/76b85610-e290-4f0e-80fe-7478b8d47d5e)

3;0x202B24D;32;0

**Comment by DePeer** [comment]
The one thing I did not do apart from unplugging, restarting etc was put the extender in ext 2 (shame on me, sorry) from that one it works so maybe a hardware thing?  For now I am 'saved' as one extender gives me enough to go on in my cabinet. Thanks. 
Should you have any knowledge about #200 (Pioneer UDP-LX500) that would be the last component that needs to be added..

**Comment by DePeer** [comment]
So this one, for me, is finished.
