### ISSUE TITLE
LAN Port LED to be off by default

### ISSUE THREAD

**Issue by ijsklont** [unfoldedcircle/bug-reports#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

LAN port LED is always on by default when no ethernet cable is connected. This is not the proper behavior for a LAN port LED as already concluded in #36. 

Please create the option to power-off the LAN port LED, when no ethernet cable is connected.

**Comment by zehnm** [comment]
I'll check the firmware within the next 2 weeks, together with #178

**Comment by zehnm** [comment]
New dock firmware is almost ready and should be released within a week after some more testing. Brightness 0 now disables status & etherned LEDs, except for setup, identify, ota and configuration reset events.

**Comment by zehnm** [comment]
Fixed in 1.7.4
