### ISSUE TITLE
[bug] Scrolling through Home Assistant entitites list resets to top

### ISSUE THREAD

**Issue by mvdwetering** [unfoldedcircle/bug-reports#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When scrolling through the entities list of Home Assistant the list scroll position resets to the top. I get the impression that it loads new entities when that happens as the scrollbar knob gets smaller when that happens.

### How to Reproduce

1. Go to the HA integration
2. Scroll the  list of available entities
3. After scrolling a bit the list position resets to the top

### Expected behavior

Able to keep scrolling.

### System version

v1.5.2

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Confirmed, added to web-configurator bugs.

**Comment by zehnm** [comment]
Fixed in 1.6.0
