### ISSUE TITLE
[feature request] Always display battery percentage

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you tap and hold the battery symbol on the remote, the remaining battery charge is also displayed as a percentage value. Unfortunately, this is reset after a restart. There should be a setting that permanently displays the percentage.

**Comment by janusloo** [comment]
If possible please make the clickable icon (profile and battery) a bit bigger to tap. At the moment it is hit and miss. I have to tap multiple times to get to the battery icon.

**Comment by pkscout** [comment]
There doesn't seem to be a way to do this from the web configurator, but if you go to the remote, close out any activity, touch the user profile, and go to settings, then under USER INTERFACE there is an option to display the battery percentage number all the time.

**Comment by kennymc-c** [comment]
@pkscout Yes, this has been added with the latest firmware update after I created this feature request. I will close this as this feature has been implemented.
