### ISSUE TITLE
Cannot Delete User Profiles

### ISSUE THREAD

**Issue by spamoni4** [unfoldedcircle/bug-reports#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just got the remote and started setting it up.  I noticed that there are 2 profiles with no names or anything.  I tried to delete and received an error about missing 5 parameters.  Not sure how to remove them.  Attached images of what I am seeing.

![Screenshot 2023-12-26 3 28 03 PM](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/81599887/f9939221-1e11-487a-be82-0e82fd75b1d0)
![Screenshot 2023-12-26 3 27 50 PM](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/81599887/c7441d1b-0316-4519-8135-96aa3b19bf60)

### How to Reproduce

Start the configurator and select User Intereface

### Expected behavior

Able to delete the Profiles or be able to review them.

**Comment by kennymc-c** [comment]
This is a known issue: https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/115
Workaround: Reload the page
Maybe hard to find since it's marked as closed but it still occurs with the recent firmware.

**Comment by zehnm** [comment]
@spamoni4 did this happen after updating to 1.5.2?

**Comment by spamoni4** [comment]
No, before.  I have since did a number of factory resets as I was having
other issues, and now on 1.5.2, it seems to be ok.  However, I am using the
Default profile though

**Comment by martonborzak** [comment]
The issue seems to be resolved. If it's not the case, please reopen the issue.
