### ISSUE TITLE
Select Profile on remote not possible

### ISSUE THREAD

**Issue by splattner** [unfoldedcircle/bug-reports#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I select an existing profile on the Remote I get a red error message "No Data found".
I can only add a new Profile directly on the Remote and then I'm in that profile. But after a restart or when leaving the profile and cannot select any other anymore.
In the webconfgurator I can add a profile, which then is also shown on the remote, but still, when selecting, only the red "No data found" error message.

### How to Reproduce

Select an existing Profile on the Remote

### Expected behavior

Open that profile

### System version

v1.1.1

### What part of the system affected by the problem?

Overall system

**Comment by Armadill0** [comment]
I have the same. But I think it only started happenning when I deleted a profile which was currently active. Since then I always get the error. Even with the initial profile.

**Comment by splattner** [comment]
Not sure if I did the same, but on initial configuration I didn't want to add a new profile and just use "Default", but the remote didn't let me continue. I had to add a new profile and then later I also played around with deleting profiles. Maybe I did something similar.
The webconfigurator don't let me delete the final/last profile, but when there are multiple, I was also able to delete the initial "Default" profile.

**Comment by splattner** [comment]
I reseted everyhting back to origin and started over. Now it works

**Comment by martonborzak** [comment]
I managed to replicate the issue. It happens when you delete an active profile via the web configurator. We'll look into it.

**Comment by martonborzak** [comment]
Fixed in 1.1.2
