### ISSUE TITLE
[bug]Multiple Android Devices 

### ISSUE THREAD

**Issue by datzent83** [unfoldedcircle/bug-reports#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When adding multiple Android devices only one works at a time. I have an Android projector and an Nvidia Shield. 

The android integration is 0.4.4. 

### How to Reproduce

If I add the Shield first and then project, the Shield works. If I add the projector first then the shield the project works. 

If I add a single Android device then that device would work. 

### Expected behavior

More than one android device should work.

### System version

1.5.2

### What part of the system affected by the problem?

Integration

**Comment by zehnm** [comment]
Multiple Android TV devices are not yet supported, only one device can be selected for now.

**Comment by datzent83** [comment]
Will it be implemented in the next nearest release?

**Comment by zehnm** [comment]
Multi-device instance support has been added (https://github.com/unfoldedcircle/integration-androidtv/issues/14).
New Android TV integration version will soon be released in beta channel.

**Comment by zehnm** [comment]
Included in the just released beta firmware 1.7.9 and the next public release.

**Comment by zehnm** [comment]
Fixed in release 1.7.12
