### ISSUE TITLE
Possible problem with ON and OFF activity sequences

### ISSUE THREAD

**Issue by gerryex3** [unfoldedcircle/bug-reports#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Switching between two activities in a group some commands in the OFF sequence are not being executed.  In order to debug the issue I am using a simple IR switch (that has nothing to do with the TV) that toggles each time it receives the command.  Its IR command was successfully learned by R2 and works correctly.  I added the switch toggle in both the ON and OFF sequences for the TV activity (see attached images).  Going into the TV activity I can see the switch toggle.  Going into another activity (TV's OFF sequence) and the switch does NOT toggle.  Going back to the TV activity and the switch toggles; leaving the TV activity again and no toggle.  However fully exiting the TV activity by pressing the Power button and the switch DOES toggle.

This leads me to think there is a bug in the Activity Group logic on which sequence commands to execute and which to not execute.

### How to Reproduce

Using the attached images of the ON and OFF sequences the IR switch should toggle when entering and leaving the activity.  It ONLY toggles when entering the activity (ON sequence).  Leaving the activity and no toggle.  Fully leaving the activity via the Power button and the switch DOES toggle.

### Expected behavior

Using attached the IR switch should toggle upon entering and leaving the activity.

### System version

Latest - up to date

### What part of the system affected by the problem?

Overall system

### Additional context

![TV OFF Sequence](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/154286809/b9732739-1c44-43c5-805f-7c6db95b8f2b)
![TV ON Sequence](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/154286809/732f3a92-7cfa-4fab-ba2f-c00e7a6f0ab8)

**Comment by Pebowski** [comment]
The Off sequence is not executed in the moment, only POWER_ON and POWER_OFF commands ar included in the logic.
See here under "Restrictions - Power-off sequence when switching activities"
https://support.unfoldedcircle.com/support/solutions/articles/101000508015-activity-groups

**Comment by gerryex3** [comment]
Any word on when the OFF sequences will be executed?

**Comment by kennymc-c** [comment]
@gerryex3 https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/64#issuecomment-1855965808
So hopefully in one of the next updates since the mentioned ir toggle bit feature has been already implemented

**Comment by zehnm** [comment]
Status update: option to run the off-sequence has been released in the BETA group and will be released in the public OTA channel soon.

**Comment by gerryex3** [comment]
EXCELLENT!!

**Comment by WillTriumph1** [comment]
This is pretty critocal. ETA on publ9c or hpw to get in Beta.

**Comment by martonborzak** [comment]
Running original off sequences has been added in 1.6.4.
