### ISSUE TITLE
Page background upload failing

### ISSUE THREAD

**Issue by Armadill0** [unfoldedcircle/bug-reports#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to upload a new image as a page background I get the error: `Error on upload: failed to fill whole buffer`

The image is 480x275 pixels wide as it says in the dialog. The size is 100KB. I attached it so you hopefully can debug it easier.
![office](https://github.com/unfoldedcircle/bug-reports/assets/6536990/7792dbbe-c938-49aa-921f-ba2ca4c3e4a6)

### How to Reproduce

1. Download the image I attached
2. Go to the webconfigurator and login
3. Select "User interface"
4. Select a profile
5. Press "Select background" in the middle of the page
6. Press "Upload" in the new dialog
7. Press "Select a file" and take the downloaded one
8. Press "Upload"
9. You end up with this at the bottom of the page:
![image](https://github.com/unfoldedcircle/bug-reports/assets/6536990/8889f824-c5cd-4a8b-a497-046818496b47)

### Expected behavior

Upload the image and make it available for usage.

### System version

v1.1.1

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Quick analysis:
- image size is determined while uploading the image, first junk is read and image header information is read (fail fast).
- upload junk size is dynamic and depends on client etc. In my tests it was 12 KB.
- the attached picture doesn't contain the image dimensions within the first 12 KB :-(
- the attached picture contains lots of additional metadata (device make, model, etc)
- upload worked when re-saving the image without the additional metadata.

To support a wider range of jpeg images with lots of metadata, the image dimension check would have to be postponed after the full upload (or multiple chunks have to be read).

Workaround:
- save image with minimal metadata (e.g. with export & strip metadata function in many image processing tools, or with copy / paste as new)

@Armadill0 does that work for you?
Here's the re-saved image, which I could upload:
![issue_27_resaved](https://github.com/unfoldedcircle/bug-reports/assets/17356629/d443aba6-aa8e-41b7-9806-160ea3e11cd4)

**Comment by Armadill0** [comment]
> @Armadill0 does that work for you?
> Here's the re-saved image, which I could upload:

Oh damn I even thought about removing the meta data before but I was too lazy. 😅 
Yes it works like a charm. Thank you very much! 😀 
I guess we can close this then. 🙂
