### ISSUE TITLE
[feature request] Performing software updates via the Web Configurator

### ISSUE THREAD

**Issue by alexthegreat100** [unfoldedcircle/bug-reports#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I would like to be able to carry out a software update for the remote control via the Web Configurator rather than via the remote control itself.
I would expect this option under the following menu:
Settings -> Remote control
I would also expect to be able to check for new updates or switch automatic updates on/off in this tile. In principle, the same functions as in the remote control itself.

**Comment by zehnm** [comment]
We're working on it, unfortunately it didn't make it in the 1.6 release.
Sneak peek:
<img width="597" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/8719d8d6-d201-44b3-963d-b97be70b77a0">

<img width="572" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/8296408c-ceff-41fd-a321-be2f0e35f99b">

**Comment by zehnm** [comment]
Status update: released in the BETA group, should be released in the public channel soon.

**Comment by zehnm** [comment]
Included in the just released version 1.6.4
