### ISSUE TITLE
[bug] Visual bug when moving/rearranging activities on "User interface" page

### ISSUE THREAD

**Issue by alexthegreat100** [unfoldedcircle/bug-reports#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you try to organise activities under "user interface" using drag & drop, errors occur in the UI.
When dragging the activity, not only is the "module" moved but also other screen contents.

https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/150591634/fc38c59c-870b-435a-989a-55df8d94dc8a

1. 

### How to Reproduce

1. Go to "User interface"
2. Click on a Profile
3. Try to rearrange activities by dragging (click & hold)

### Expected behavior

Move only the activity and not other content.

### System version

v1.6.1

### What part of the system affected by the problem?

Web Configurator

**Comment by kennymc-c** [comment]
This only seems to to happen in Safari. In Chrome there is a different visual bug as mentioned in #100

**Comment by alexthegreat100** [comment]
Ok, that's strange... especially when you consider that this behaviour only occurs when editing the "user interface". In all other cases (e.g. when creating activities) this principle works without any problems...

**Comment by zehnm** [comment]
Confirmed: this is a Safari issue. Works in Chrome & Firefox.

**Comment by alexthegreat100** [comment]
Can you fix that? This problem does not exist in other parts of the UI...

**Comment by zehnm** [comment]
This will be fixed in the next release

**Comment by zehnm** [comment]
Fixed in 1.6.9
