### ISSUE TITLE
Long Press

### ISSUE THREAD

**Issue by jmvenable** [unfoldedcircle/bug-reports#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are several apps that rely on a long press to activate options. I think it is sorely needed. I believe the screen has long press capability but not the buttons, particularly the OK / Enter button.

**Comment by kennymc-c** [comment]
There are already existing issues for this feature: 
https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/90
https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/56
https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/94

**Comment by martonborzak** [comment]
Closing as it's duplicate.
