### ISSUE TITLE
[bug] entity group toggle only toggles power state of first entity in group

### ISSUE THREAD

**Issue by leoschweizer** [unfoldedcircle/bug-reports#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since updating to 1.6.1, the ui toggle for entity groups will only toggle the state of the first entity in the group instead of all entities in the group. Previously all entities were toggled, which is the expected behavior.

### How to Reproduce

1. Create a group with two entities that can be powered on/off
2. Put group on a screen
3. Use toggle besides the group to power the entities on or off
4. Only the first entity will be powered on or off

### Expected behavior

All entities in the group should be powered on or off, which was the behavior previously to updating to the 1.6.1 release.

### System version

v1.6.1

**Comment by zehnm** [comment]
Confirmed: we'll fix it

**Comment by martonborzak** [comment]
Fixed in next release.

**Comment by zehnm** [comment]
Fixed in the just released version 1.6.4
