### ISSUE TITLE
Creating same integration via REST multiple times is possible

### ISSUE THREAD

**Issue by Talkabout** [unfoldedcircle/bug-reports#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Via REST it is possible to create the same integration (with same driver_id) multiple times, is this expected?

### How to Reproduce

1. create an example integration via rest:

{
	"driver_id": "test",
	"name": {
		"de": "TEST",
		"en": "TEST"
	},
	"driver_type": "EXTERNAL",
	"driver_url": "ws://test.local:8080",
	"token": "test",
	"auth_method": "HEADER",
	"version": "0.1",
	"icon": "uc:cool",
	"enabled": true,
	"device_discovery": false,
	"setup_data_schema": null
}

2. POST the same integration definition again
3. both integrations are visible

### Expected behavior

The second request with the same driver_id should be rejected.

### What part of the system affected by the problem?

Integration

**Comment by zehnm** [comment]
Closing: invalid

Creating the same driver again with identical `driver_id` results in response code 422 unprocessable entity, with body:
```json
{
    "code": "ALREADY_EXISTS",
    "message": "Data already exists"
}
``` 

Tested with provided example: `POST /api/intg/drivers` and body:
```json
{
    "driver_id": "test",
    "name": {
        "de": "TEST",
        "en": "TEST"
    },
    "driver_type": "EXTERNAL",
    "driver_url": "ws://test.local:8080",
    "token": "test",
    "auth_method": "HEADER",
    "version": "0.1",
    "icon": "uc:cool",
    "enabled": true,
    "device_discovery": false,
    "setup_data_schema": null
}
```

Only if `driver_id` is omitted, the driver can be registered multiple times, but then a `driver_id` is automatically assigned. See: https://github.com/unfoldedcircle/core-simulator/blob/v0.33.0-beta/core-api/rest/openapi.yaml#L1562-L1584

**Comment by Talkabout** [comment]
Hi @zehnm ,

you are right, the integration was created with a random driver_id because of a typo, sorry!
