### ISSUE TITLE
[feature request] Add Harmony Hub integration

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/bug-reports#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I think a lot of people have a Harmony Hub, perhaps even you, why not use them with UC? I would have 2 advantages:
1. Support for a lot of devices without learning
2. an IR extender for separate rooms

(3). the UC can teach herself by sending a command by Harmony while learning with the own hub.

Ralf

**Comment by WillTriumph1** [comment]
A good request. If it could be used as a passthru for the ir blaster it would be very useful

**Comment by tiki-ftl** [comment]
Would like to use such a feature too.
Thank you!

**Comment by Kat-CeDe** [comment]
Hi not needed anmore there is a community integration which does it.

**Comment by WillTriumph1** [comment]
This should not be closed until it is integrated, not requiring another computing device and container.

**Comment by kennymc-c** [comment]
@WillTriumph1 For uploading integrations to the remote there is this existing requests which was announced to be implemented after Bluetooth support: https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/79

**Comment by WillTriumph1** [comment]
Noted: I see this one is not on the integrations page so hopefully will be added.
