### ISSUE TITLE
[feature request] German translation for activity status

### ISSUE THREAD

**Issue by alexthegreat100** [unfoldedcircle/bug-reports#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The status of the activity is displayed under the respective activity. This status is either "On" or "Off". The English terms "On" / "Off" are also used in German.
I would be pleased if this could be adapted and the terms "An" and "Aus" could be used here.

![IMG_0600](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/150591634/ec1d3eca-3429-44a3-b1a6-e58962ae4632)

**Comment by kennymc-c** [comment]
The same applies to entity states (on, off, available and unknown)
Apparently the strings for on, off and unknown have been already translated and approved via Crowdin for a few month now: https://crowdin.com/editor/uc-remote-ui/37/en-de?view=comfortable#5243

Other things that are not translated:
All tipps pages (home long press/show tipps)
Blinds status (open/closed) (String are approved: https://crowdin.com/editor/uc-remote-ui/37/en-de?view=comfortable#4841)
Media Player status (e.g. playing), show as "ist playing" on the remote
Integration status (e.g. connected, only remote ui)

**Comment by zehnm** [comment]
@martonborzak can you check remote-ui if the entity & activity states are mapped to resource texts?
If the technical entity state enum is directly displayed in the UI then that would be sub-optional :-)

**Comment by JotWee** [comment]
@zehnm any update on this? In case you end help, I would be happy to support you. If I receive a list of all texts to be translated, I will do the German translations.

**Comment by zehnm** [comment]
Fixed in 1.6.9. Initial translations for German, French and Swiss are included. If something shouldn't match or you feel there's a better translation for a specific entity state, then please raise an issue on the [Remote UI Crowdin project](https://crowdin.com/project/uc-remote-ui).
