### ISSUE TITLE
Different Dock Firmware version but no update available

### ISSUE THREAD

**Issue by SidM01** [unfoldedcircle/bug-reports#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have 3 different docks and two have version 0.9.2 and one has version 0.9.0 but no update is shown as Available

### How to Reproduce

1. Go To Integrationen & Docks.
2. Go To "Wohnzimmer Dock" and klick search for Updates.
3. nothing happens

### Expected behavior

Find a Update

### System version

v1.1.1

### What part of the system affected by the problem?

Overall system

**Comment by zehnm** [comment]
Reason: there's no dock firmware available in the OTA release channel. All shipped docks should have had the latest 0.9.2 version.
I'll retest and add the latest firmware as OTA update.

**Comment by zehnm** [comment]
The 0.9.2 dock firmware is available as OTA download. Sorry for the delay!

Open the web-configurator and if it's not already showing an available update, open the dock(s) and click "Check for update". Then it should show this:

<img width="542" alt="image" src="https://github.com/unfoldedcircle/bug-reports/assets/17356629/6d406013-142f-43d7-8150-f255f6cf8ab5">

Note: there's a UI bug after the update. It will still show the old version after a successful update. Simply refresh the page for now and it will update :-)
