### ISSUE TITLE
[feature request] Media player menu/cursor/back/enter buttons not mapped in entity ui

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening a media player entity from a profile page that supports the menu and dpad features the corresponding buttons are not woking. The home, back and dpad buttons are still used for remote ui navigation instead of controlling the entity.

### How to Reproduce

1. Add a media player entity that supports the menu and dpad feature to a profile page
2. Open the media player from the remote ui
3. Press the home, back or dead buttons

### Expected behavior

Menu, dpad and back buttons should control the entity and not the remote ui

### System version

1.6.7

### What part of the system affected by the problem?

UI

**Comment by martonborzak** [comment]
I have not been able to reproduce this with Apple TV entity.

Please provide more information:
- what integration provides the entity
- logs for the UI service after reproducing the issue

**Comment by kennymc-c** [comment]
The internal Apple TV Integration works for as well. But besides volume control it doesn't work for the external Denon integration (https://github.com/splattner/remotetwo-integration-denonavr). If I map these commands to a button within an activity it works as expected.
Unfortunately I can't test this with the Denon UC internal integration since it doesn't support menu and dpad features.

UI logs: 
[UCR2_logs_2024-02-07.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14200038/UCR2_logs_2024-02-07.txt)

**Comment by martonborzak** [comment]
I don't see directional keys pressed in the logs. The integration needs to declare the device class correctly, otherwise features might not work. As this works with all internal integrations, I assume it's an issue with the 3rd party integration.

**Comment by kennymc-c** [comment]
New log with more buttons pressed: 
[UCR2_logs_2024-02-07.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14200229/UCR2_logs_2024-02-07.txt)
Ignore the 500 errors as they probably happened because I pressed buttons to fast in succession. 
The external log from the integration shows no entries if I press one of the affected buttons. What does work is volume, mute and play/next/previous
All functions and features from this integration are working inside an activity and also gets logged on the integration side.

**Comment by martonborzak** [comment]
I see the media player is receiving the button presses. Please check with the integration what device class they use as I see nothing wrong in the ui app.

**Comment by kennymc-c** [comment]
It's using the receiver device class: https://github.com/splattner/remotetwo-integration-denonavr/blob/e4cba6f9ace90d3273b446657b15a2aca634b9bf/pkg/clients/denonavr/denonavrclient.go#L100

**Comment by martonborzak** [comment]
We'll expand the mappings regardless of the device class.

**Comment by martonborzak** [comment]
Button mappings have been added in 1.7.4.

**Comment by kennymc-c** [comment]
Is it expected that if an integration is only supporting the menu feature and has no dedicated home command that there is no button mapped to menu? If I press the home button this is still used for the remote ui navigation but dpad and back is working now. Maybe menu could be mapped to the home button on the remote is this case if the home button feature is not supported.
