### ISSUE TITLE
[bug] Activity on and off Sequence getting stuck after 1.6.9 update

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After installing the 1.6.9 update on and off sequences of activities getting stuck at either the first or last step. The overlay doesn't disappear and you have to press the back or home button to get back to the profile pages. Sometimes the activity state has changed to error after that. After starting the activity again it works without errors. All commands including the command where the sequence stops are executed but everything after that will not be executed.

### How to Reproduce

1. Start or stop an activity

### Expected behavior

The on sequence should finish without errors

### System version

1.6.9

### What part of the system affected by the problem?

UI

**Comment by somm86** [comment]
I can confirm that too. the same with macros.

**Comment by Pnuts76** [comment]
Same here.

**Comment by kennymc-c** [comment]
This even happens if both sequences are empty. If it stucks at the last step the activity ui automatically opens when you press back or home. I think this wasn't the case when it gets stuck at the first step. But this only happened once after the update. After that it was always the last step.

Edit: When you start an activity for the first time it's the first step. Text shows step 0/85 even if the sequences are empty. When you start it again this text is missing. For stop sequences it seems to be always the last step.

**Comment by kennymc-c** [comment]
Here are some logs.

[UCR2_logs_2024-02-07.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14187470/UCR2_logs_2024-02-07.txt)

They also include a suspiciously long reboot. I did the reboot because some activities that I had moved in the web configurator in the position on the profile pages suddenly had their old name again, which I had actually changed several days ago. After the reboot the new names were back. I think this problem has happened before when moving entries directly via the remote ui.

**Comment by martonborzak** [comment]
There were no changes regarding activities or the loading screen in firmware 1.6.9.
I have not been able to reproduce this on multiple devices and configurations.

Please provide more details about your setup:
- How does the on and off sequence looks
- What entities are included in the activity and if these entities are also present on a page in the ui or just used in the activity

**Comment by martonborzak** [comment]
Digging a bit deeper, the issue is now identified, fix is in the works, we're trying to get an update out as soon as possible.

**Comment by zehnm** [comment]
New release is being built and available later today

**Comment by TrialMaster** [comment]
I’ve had no issues with 1.6.9, the next release will not introduce issues I hope.

**Comment by kennymc-c** [comment]
Thanks, solved with 1.6.10
