### ISSUE TITLE
HW Issue - Display stopped working

### ISSUE THREAD

**Issue by eughenes** [unfoldedcircle/bug-reports#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is not a bug but a HW issue, and I can’t find a place to report it on the web site to ask for a repair or replacement. The display is not working anymore, tried to restart the remote but it doesn’t work.

### How to Reproduce

Issue specific to my remote

### Expected behavior

Should work

### System version

Latest

### What part of the system affected by the problem?

Overall system

**Comment by kennymc-c** [comment]
Have you tried a factory reset after making a backup? https://support.unfoldedcircle.com/support/solutions/articles/101000437595-how-to-factory-reset-the-remote-

Otherwise just contact the support via mail (support@unfoldedcircle.com) or use the form on their website.

**Comment by eughenes** [comment]
Yes, but to complete factory reset process the display must work.
I'll try to send a message to the mail address. Thanks.

**Comment by Quinterly** [comment]
> Yes, but to complete factory reset process the display must work. I'll try to send a message to the mail address. Thanks.

You can do a factory reset from the Web Configurator

![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/151413090/81f5757b-24e3-4c7c-ac42-fdb5e5711691)

**Comment by eughenes** [comment]
Unfortunately, to get there you need a PIN code which is shown in the settings on the remote, which requires the display to work. Don't know if there are alternate ways to get it or a hardware reset mechanism.

**Comment by kennymc-c** [comment]
The PIN is always the same if it not gets rotated by you via the remote UI. Even after a restart. I guess you haven't saved it anywhere else?

**Comment by WillTriumph1** [comment]
This is another example of a hassle with the person working for the remote vs the other way around. If you use the configurator at a place where you don't have it written down , then you recycle and you roll it and start again. How about setting it vs pseudo-randomizing.

**Comment by eughenes** [comment]
No, I didn't write down, unfortunately. For sure it would have been better a standard password protection or a manually set pin, I agree.
Let's see what the support will tell me.

**Comment by WillTriumph1** [comment]
On the display I had the black screen of death after reboot of remote. I held down the power hard button on the remote for about 30 seconds and it came back to life. Lots of holding and swearing later it started booting. Fir service get ready to wait about a week for support.

**Comment by eughenes** [comment]
I'll try again, while I wait for a feedback from support, I just tried to power off and on only a couple of times.

**Comment by martonborzak** [comment]
It's handled by support, so closing here.
