### ISSUE TITLE
[bug] AppleTV - internal error please try again later

### ISSUE THREAD

**Issue by Depechie** [unfoldedcircle/bug-reports#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Adding the AppleTV integration works, but actually using it is not great.
Regularly I get the red popup message stating "Internal error - please try again later".

### How to Reproduce

Just use the remote with the AppleTV configured.

### Expected behavior

Using the AppleTV should always be responsive and working,

### System version

v1.6.10

### What part of the system affected by the problem?

Integration

### Additional context

[UCR2_logs_2024-02-11_appletv.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14232066/UCR2_logs_2024-02-11_appletv.txt)

**Comment by Depechie** [comment]
[UCR2_logs_2024-02-11_AppleTV.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14234285/UCR2_logs_2024-02-11_AppleTV.txt)

New set of debug logs with some strange 'power is blocked' exceptions

**Comment by martonborzak** [comment]
We've seen the same `power is blocked` exceptions. Looking into it.

**Comment by Depechie** [comment]
In reference, I too have this https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/298 also.
In other words, sometime the activity starts but I then get those Internal error popups.
Or the activity won't start because of the issue mentioned in #298

**Comment by Depechie** [comment]
[UCR2_logs_2024-03-09.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14548006/UCR2_logs_2024-03-09.txt)

It seems the integration got a bit better. At first things seemed to work fine, but later again trying to start the with the AppleTV it would not get passed the turn on step of the AppleTV.
Showing the red dot and putting the integration in error mode.

Added the logs, running 1.7.4

**Comment by Depechie** [comment]
![IMG_3230](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/351693/f4aed6b9-3b6a-45cc-ab85-42d3a2c9818b)
[appletv_UCR2_logs_2024-03-12.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14577154/appletv_UCR2_logs_2024-03-12.txt)

Still problems... running 1.7.5 now // @zehnm

**Comment by Depechie** [comment]
[UCR2_logs_2024-03-21.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14705602/UCR2_logs_2024-03-21.txt)

v1.7.7

Still sometimes I get the service unavail message. Both at startup of the activity or during run of the activity and wanting to trigger an AppleTV command

**Comment by Depechie** [comment]
Did some major rework of my network in Unifi and have been using the remote for a couple of days now, without any failures.
Always thought it had to be network related, still not sure how I could have identified this. Because not sure how I could handle it when problems should return.

**Comment by aihk8** [comment]
Hi @Depechie. I’m having almost the same issue on a Remote 3 after moving to Unifi. Would you mind sharing which Unifi settings you changed to fix failures? Thanks!

**Comment by Depechie** [comment]
To be honest, it never got away fully :/ 
Still often I get the red banner to try again later.

What I did was playing with the channel width, transmit power and channel of each AP.
