### ISSUE TITLE
[bug] activity groups are not save with Backup / Sichern

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/bug-reports#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created 5 groups for rooms and added activities to these groups. When I made a backup of my configuration the folder activity_groups in the zip file UCR2_2024-02-12_113020.backup was empty.

### How to Reproduce

1. create activity groups
2. add activities to the groups
3. go to Einstellungen/Setup(?)
4. choose Backup/Sicherung
5. choose download/herunter laden
6. open .backup file as zip
7. activity_groups is empty

### Expected behavior

I expect that the configuration of the groups is in that folder

### System version

1.6.10

### What part of the system affected by the problem?

Web Configurator

**Comment by kennymc-c** [comment]
I can't reproduce this. My activity groups folder from the backup is not empty and contains a json file for every group.

**Comment by Kat-CeDe** [comment]
You are correct. I created groups in the user interface option. Now I created groups in the activity option and they were saved.

What are the groups in user interface for?

**Comment by kennymc-c** [comment]
The normal groups can be compared more to folders. They are more for organization and keeping things clear and have no other special function.
