### ISSUE TITLE
Speed up dock & integration connection logic

### ISSUE THREAD

**Issue by zehnm** [unfoldedcircle/bug-reports#320]
From testing with various networking gear and user reports, the (re-)connection time to the dock and external devices can be improved in certain environments.
Networks with slow IP address assignments will see most benefits from the new connection logic.

Changes:
- Additional connectivity tests after WiFi connection
- Provide more network state information to local integration drivers to optimize network communication

This affects the dock connection, device connections of local integrations and connecting to external integrations.

**Comment by zehnm** [comment]
Part of 1.7.4

**Comment by kennymc-c** [comment]
@zehnm Is there any reason why this is still listed under preview features as this issue has been closed over 2 years ago?

**Comment by zehnm** [comment]
This feature flag will be removed in an upcoming release.
