### ISSUE TITLE
If buttons are changed from text to symbol, text is still display together with symbol

### ISSUE THREAD

**Issue by Yezariael75** [unfoldedcircle/bug-reports#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you add a button with text and later change it to symbol, the old text is still display together with the symbol

### How to Reproduce

1. Go to activities
2. Change a text button to symbol

### Expected behavior

Only the symbol is displayed, not the old text

### System version

1.1.1

### What part of the system affected by the problem?

UI

**Comment by SidM01** [comment]
yes me to

**Comment by RyanEaves** [comment]
Workaround for this is to switch back to text, put in a space, and then switch back to icon.

**Comment by zehnm** [comment]
Fixed in current version
