### ISSUE TITLE
[bug] Scrollbars displayed on custom icons page

### ISSUE THREAD

**Issue by albaintor** [unfoldedcircle/bug-reports#336]
Since a few firmware updates (or maybe this is due to my growing collection of icons), the icons grid is shown with multiple vertical scrollbars for each icon.
Here is a screenshot of my icons page :
<img width="1020" alt="image" src="https://github.com/unfoldedcircle/core-api/assets/118518828/57e5325b-e219-4d51-b8ab-062e16a0198c">

While debugging CSS through my (Chrome) browser, I found that disabling "overflow-x : hidden" on .ressources--list--item resolves the problem as shown below :
<img width="1232" alt="image" src="https://github.com/unfoldedcircle/core-api/assets/118518828/60393853-05a8-494e-be93-ffe9f932c0c7">

## Description
Go in the icon page to customize an icon for a button, then in the custom icon page : the icons are all shown with an individual vertical scrollbar

## Expected behavior
No vertical scrollbar as the icons should fit in the grid

## Screenshots
See ^^

## Your Environment
Last version of the firmware : 1.7.4 (issue since at least 2 firmware releases)
Chrome browser

**Comment by RC-Thoughts** [comment]
Seems to be related to length of icon-name, icons with short name are shown normally:

![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/18365352/477a142d-6a32-4f79-907b-8d481b98fa98)

**Comment by zehnm** [comment]
We'll fix this, it's in the web-configurator backlog.

**Comment by zehnm** [comment]
Fixed in next release

**Comment by zehnm** [comment]
Fixed in 1.7.7

**Comment by albaintor** [comment]
Great thank you
