### ISSUE TITLE
[bug] Remote 2 firmware 1.7.4 still reports Home Assistent integration version 0.7.0-dirty

### ISSUE THREAD

**Issue by loekf** [unfoldedcircle/bug-reports#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The firmware released on March 8, 2024 still has the HA integration having version 0.7.0-dirty.

My other integrations report the latest versions as on github (e.g. Denon Receivers and AppleTV).

I suspect release 0.8.2 as listed on github did not make it into the remote firmware release or is wrongly reported.

### How to Reproduce

Check for the version in the inegrations overview on either the remote or the web UI.

### Expected behavior

I would expect the latest HA integration release is in.

### System version

1.7.4

### What part of the system affected by the problem?

Integration

### Additional context

None

**Comment by zehnm** [comment]
Firmware 1.7.4 contains Home Assistant integration 0.8.1. Version 0.8.2 doesn't contain new functionality.

> I would expect the latest HA integration release is in.

This is not the case. A new firmware release is shipped with the integration versions it has been tested with and not necessarly with the latest releases.

> The firmware released on March 8, 2024 still has the HA integration having version 0.7.0-dirty.

I've noticed one UI bug where after an update the old version is shown, until the next restart. The API reports the correct version (after the integration is running and a connection has been established).

@martonborzak I'm assigning you this issue to fix the integration view in the remote-ui.

**Comment by martonborzak** [comment]
Fixed in next release.

**Comment by zehnm** [comment]
We'll publish an update by tomorrow.
It's already available in beta group.

**Comment by zehnm** [comment]
Fixed in 1.7.5
