### ISSUE TITLE
[bug] Home Assistent integration says service unavaible after finishing the setup

### ISSUE THREAD

**Issue by loekf** [unfoldedcircle/bug-reports#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to set up HA it finishes with service unavailable (in red). This is via the web UI. When doing this on the remote this does not happen.

In the integrations’ overview you see “connecting” all the time.

### How to Reproduce

Firmware 1.7.4, with the HA integration reported as 0.7.0-dirty
Home assistent: 2024.3.0

### Expected behavior

Nothing to add, it should work as reported by others.

### System version

1.7.4

### What part of the system affected by the problem?

Web Configurator, Integration

### Additional context

I tried to set up the timeout to 30 seconds, but no effect.

**Comment by loekf** [comment]
Found a solution. I have to replace homeassistent.local with the actual IPv4 address on my network.

**Comment by martonborzak** [comment]
Looks like mDNS is not configured correctly or not working on your network. mDNS is required if hostnames are used ([Network requirements](https://support.unfoldedcircle.com/support/solutions/articles/101000508890-network-requirements)).

Glad it's working now.
