### ISSUE TITLE
[bug] Apple TV integration corrupt after updating to 1.7.4

### ISSUE THREAD

**Issue by henrikwidlund** [unfoldedcircle/bug-reports#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After updating the firmware to 1.7.4 my existing Apple TV integration no longer worked. I've tried to re-run the integration setup, but it fails with error `NOT_FOUND`. I noticed that when I select the integration to setup it's called Apple TV2.
<img width="645" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/4659350/4e8c962b-c0cc-4dae-ad0c-cbed857ca9f7">
<img width="694" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/4659350/ae5672ee-36af-459c-8f3e-5b517f8ba187">

Tried restoring from a backup made before the update without result.

Because of this I can't use the Apple TV integration. I suspect it has something to do with the fact that it for some reason has been renamed and that isn't expected, so it's not found?

[UCR2_logs_2024-03-09-3.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14546521/UCR2_logs_2024-03-09-3.txt)

### How to Reproduce

1. Update a remote with Apple TV integration setup running 1.6.10 to 1.7.4
2. Try to use the integration - buttons aren't responding
3. Try to reconfigure the integration - fails with `NOT_FOUND` (integration name shows up as Apple TV2 in the title when you open it)
4. Delete the integration and attempt to add it anew - Still named as Apple TV2, fails with `NOT_FOUND` again.

### Expected behavior

Apple TV integration should be working after updating the firmware, and should have the same name.

### System version

1.7.4

### Additional context

Dock firmware 0.10.0
Apple TV integration version 0.13.3 according to remote.

**Comment by henrikwidlund** [comment]
I got it working again, not sure what helped, but this is what I did:
1. Restore from an even older backup
2. Restore from backup made with 1.7.4
3. Remove device through remote (note: integration not deleted)
4. Add device through the remote
5. Works

**Comment by zehnm** [comment]
Found the issue, an invalid driver metadata file for development got into the release!
I'll create a patch release asap

**Comment by zehnm** [comment]
We'll publish an update by tomorrow.
It's already available in beta group.

**Comment by henrikwidlund** [comment]
Super, thanks for the quick fix!
I noticed I'm also getting the same error code when trying to add a Denon integration. Could that one also be affected by the same issue? Should I open a new bug for it?

**Comment by zehnm** [comment]
Denon integration hasn't changed in 1.7.x. Please check the logs (some AVRs take several minutes after a cold boot to be reachable on the network) and open a new issue.

**Comment by henrikwidlund** [comment]
You're right, it's not related. Opened a a new issue #342.

**Comment by henrikwidlund** [comment]
1.7.5 solved the issue with the name, but I'm still getting the `NOT_FOUND` error. This might be because the devices are on different subnets. The devices were on the same subnet when I initially added the Apple TV integration. Restoring from a backup that has the integration setup now works though.

[UCR2_logs_2024-03-10-3.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14549974/UCR2_logs_2024-03-10-3.txt)

**Comment by martonborzak** [comment]
mDNS does not work across different subnets. If you have a setup like that, you can setup the Apple TV by providing its ip address.

**Comment by henrikwidlund** [comment]
My router does have support for forwarding mDNS between different subnets, and it finds the device using auto discovery, but when I select the device in the dropdown and click on next it shows me `NOT_FOUND`. Entering the IP results in the same error message.

[UCR2_logs_2024-03-10-4.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/14550129/UCR2_logs_2024-03-10-4.txt)

**Comment by zehnm** [comment]
Apple TV doesn't work in a different subnet, even if the IP address is entered. (Technical detail: see [pyatv unicast scanning](https://pyatv.dev/documentation/concepts/#scanning)).

**Comment by zehnm** [comment]
Closing issue: integration name & id has been fixed in 1.7.5
