### ISSUE TITLE
[bug] Remote pages - Hardware buttons only react to long press

### ISSUE THREAD

**Issue by henrikwidlund** [unfoldedcircle/bug-reports#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While in the dialog dedicated to individual remotes on the remote my hardware buttons only sends commands when doing long presses, even though I've only configured short presses. This doesn't affect soft buttons. Activity pages are unaffected.

### How to Reproduce

Pre req: Hardware buttons mapped to commands on a device.

1. Open an activity
2. Press the activity title on the top to open the dialog that lists the devices that are included in the activity
3. Pick one that has hardware buttons mapped to a command
4. Short press a hardware button - nothing happens
5. Long press a hardware button - short press command is executed

### Expected behavior

Hardware buttons mapped on a remote (device) page should send the short press command when a short press is executed.

### System version

1.7.4

### What part of the system affected by the problem?

Core, Overall system

**Comment by kennymc-c** [comment]
I can confirm this and some commands on buttons that have a ui navigation function are not working at all.

**Comment by JoaoPPCastelo** [comment]
Having the same issue. Use the hardware buttons to control the TV and they don't work. Tested the IR codes using the config app everything is correct. Also tested to remove the config for the buttons and add again but same issue.

**Comment by zehnm** [comment]
Same issue as reported here: https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/94#issuecomment-1986821343
Fixed in the next patch release out by tomorrow.
I'm keeping this issue open for better visibility.

**Comment by henrikwidlund** [comment]
I can confirm that this was fixed in 1.7.5

**Comment by zehnm** [comment]
Closing issue: fixed in 1.7.5
