### ISSUE TITLE
Can't download update 1.7.5

### ISSUE THREAD

**Issue by tastyrepublic** [unfoldedcircle/bug-reports#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can't update from 1.6.10 to 1.7.5, try reboot a few times and it just keep downloading. The dock updated to the latest version successfully. I try to use different internet connection and the problem still there.

### How to Reproduce

click download in the update.

### Expected behavior

finish download and install the latest firmware.

### System version

v.1.6.10

### What part of the system affected by the problem?

Overall system

**Comment by zehnm** [comment]
The download might take a while and it's best to leave the remote in the dock while downloading. If it still doesn't work then please provide the logs from the "Core service" (web-configurator, settings, development: Logs).

**Comment by tastyrepublic** [comment]
Problem solved, put it in the dock for a day and finish the download. thank you so much.
