### ISSUE TITLE
[bug] Removed entities from a profile group do not appear in the list again

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Entities removed from profile groups only reappear in the list on the right after reopening the group settings. If you have previously searched for the missing entity, the search results are still displayed on the right after reopening, even though no search term has been entered. The entity is also removed without clicking on Save just by closing the window. When adding an entity, however, you have to click on save.

### How to Reproduce

1. Create a profile group and an entity
2. Remove the entity
3. Search for the entity on the right
4. Close the group settings
5. Reopen the group settings

### Expected behavior

Removed entities should reappear in the list on the right immediately afterwards. In addition, the removed entities should only be removed by clicking on Save and not when you just close the window. Alternatively, the save button can be removed completely and changes are saved directly, as is the case with other actions

### System version

1.7.5

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Confirmed: the included entities list is not reloaded when opening the dialog.
- A removed entity is not automatically deleted
- Save button still has to be used to remove the entity from the group
- Manually reloading the page shows the correct data

**Comment by zehnm** [comment]
Fixed in next release.

**Comment by zehnm** [comment]
Part of beta release 1.7.10

**Comment by zehnm** [comment]
Fixed in release 1.7.12
