### ISSUE TITLE
AppleTV integration Power-Off command will toggle the AppleTV power state since update to 1.7.5 (or 1.7.4)

### ISSUE THREAD

**Issue by hprotter** [unfoldedcircle/bug-reports#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since R2 firmware 1.7.5 (maybe also 1.7.4) the Power-Off command of the native AppleTV integration will toggle between power on and off state of the AppleTV. Due to this error the AppleTV will be powered on if R2 sends a Power-Off command when the AppleTV is already in off state. I never noticed this behaviour in older firmware versions.

"Power-Off" is maybe also called "Suspend"? I don´t know the correct name in the English web-configurator. In German web-configurator this AppleTV integration function is called "Ausschalten".

### How to Reproduce

1. Send a Power-Off command with AppleTV integration to the connected AppleTV
2. The AppleTV power state is toggled and switched from off to on, or from on to off depending from the actual state

### Expected behavior

The Power-Off command of the AppleTV integration should switch off the AppleTV, independently from the actual on or off state and should not be a toggle power command.

### System version

1.7.5

### What part of the system affected by the problem?

Integration

### Additional context

The behaviour of the "Power-On" command is correctly a discrete power on and not a toggle. So just the "Power-Off" has this wrong behaviour.

**Comment by zehnm** [comment]
Confirmed: when the device is in standby, any command including power off, will wake up the device.
This will be fixed in the next release.

**Comment by zehnm** [comment]
Fixed in 1.7.7

**Comment by hprotter** [comment]
Great! Thank you for your fast reaction and the bug fix!
