### ISSUE TITLE
[bug] Editing of activity GUI is not working after some added commands

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/bug-reports#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created a page with 4x6 elements and put there 12 text elements with width 2 and selected commands to test. After that I created a page 2 and wanted to do the same but now the text and also picture elements could not be placed correctly anymore and also the name of a text element ist not take. See attached image
![edit gui](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3451049/592f5893-703a-464a-876a-cc8dfc590907)
I already produced this twice. I had the same effect on the sesond page after I put 30 1x1 text elements on page 1 in a 5x6 grid. I could not find any regularity.

### How to Reproduce

1. Edit activity gui
2. put 12 commands with text boxes of width 2 on page 1
3. create a 2nd page
4. try to freely place a new text element on page 2

### Expected behavior

4. text elements could also be freely placed

### System version

1.7.5

### What part of the system affected by the problem?

Web Configurator

**Comment by Kat-CeDe** [comment]
I forgot I used latest windows version of chrome but also had the effect on chrome for Linux.

**Comment by martonborzak** [comment]
I have not been able to reproduce this.

**Comment by Kat-CeDe** [comment]
Hi,
I am not sure if it helps but I created a small video which you can find at www.rbsoft.de/UC_Activity_GUI.mkv (1.5MB)
I used Windows 10 x64 with latest Chome and Thunderbird.  I connected remotely to the UC but the same happens if I configure locally. Sometimes I could use a second page and I get problems on the 3rd page. I do not know if it makes a difference the used activity has 5 entities, 3 IP based and 2 IR based.

If you want to test it by yourself I can give you the URL and PIN.

Ralf

**Comment by zehnm** [comment]
We have a fix in the next release which should hopefully solve it. At least I was no longer able to reproduce it (for me it only happened when using more than 2 pages).

**Comment by zehnm** [comment]
Part of beta release 1.7.10

**Comment by Kat-CeDe** [comment]
Hi,
good job. On 1st look I would say 99%. It is a lot better now but I found small, but this time not tragic, point. I can move elements in at least one row more than I configured. See picture.
![1710](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/3451049/e6d8453d-fd23-448a-8295-de2965a62870)

I could not reproduce it so ignore it for the moment.
