### ISSUE TITLE
Activity LED of the LAN port on the dock burns even when no LAN cable is connected

### ISSUE THREAD

**Issue by ijsklont** [unfoldedcircle/bug-reports#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Activity LED of the LAN port of the dock constantly burns, even when no LAN cable is connected to it.

### How to Reproduce

1. Connect power to dock
2. Disconnect any LAN cable if this is connected
3. View LED behavior of LAN port on the back of the dock

### Expected behavior

Activity LED from LAN port to be off when no LAN cable is connected.

**Comment by ijsklont** [comment]
Additional question, is it intended behavior for the LAN port activity LED to also react to the brightness settings for the front LED?

**Comment by martonborzak** [comment]
There are two LEDs on the ethernet port. One (green) is always on, indicating that the port is ready. The amber one turns on when a cable is connected.

The LEDs are controlled by the same brightness settings by design. 

It seems like everything works as intended :)

**Comment by tomlut** [comment]
It's a minor issue but that's not the way LAN port LEDs are used. Should be:

* Connection State LED: Amber = 1000Mbps, Green = 100Mbps, Off = 10Mbps or cable disconnected
* Connection Activity LED, flashes during data transfer.

A quick Google search for LAN port LEDs will confirm this.

**Comment by lutzh86** [comment]
![image](https://github.com/unfoldedcircle/bug-reports/assets/45604968/1b51e85e-bbbf-4152-9816-3db8a7f1892c)

**Comment by lutzh86** [comment]
![image](https://github.com/unfoldedcircle/bug-reports/assets/45604968/f472fdb0-e659-43b6-b45b-9220e2ffbdcc)

**Comment by ijsklont** [comment]
When will this be solved?

**Comment by hprotter** [comment]
When will this be solved? The constant glow of the LED, even without a LAN cable plugged in, is extremely annoying, especially in the bedroom and that's really not the way LAN port LEDs are used.

**Comment by tomlut** [comment]
It has already been solved. This **is actually how the majority of LAN port LEDs are used** and this is how the port LEDs now function:

* Connection State LED: Amber = 1000Mbps, Green = 100Mbps, Off = 10Mbps or cable disconnected
* Connection Activity LED, flashes during data transfer.

If it annoys you in the bedroom you have two options:

1) Force a 10Mbps connection on the switch port it is connected to (requires a managed network switch, and only turns off the steady connection state LED). 
2) Use a piece of black electrical tape to cover the LEDs  (requires black electrical tape, turns off both LEDs).

**Comment by ijsklont** [comment]
Its not solved yet. I still get the led burning even when no LAN cable is connected.

My dock has been updated to 0.9.2

**Comment by tomlut** [comment]
I just tested this, you're right the activity LED stays on with the cable disconnected :/

However for the bedroom bright light issue, in the web configuratior if you click on "Integrations & Docks" in the hamburger menu (top right of page) then select your dock, you can set the port LED brightness to 0.

![Untitled](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/10679300/c53e6c54-e2dc-4559-851b-e5b9578e5434)

**Comment by ijsklont** [comment]
OK I see that to, but then it's still just a temporary fix as thst setting dimms all led on the dock.

**Comment by tomlut** [comment]
That's why I said:

> for the bedroom bright light issue
