### ISSUE TITLE
[bug] German translation of the previous command is ambiguous and missing on Crowdin

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the German translation there are two commands with the same name in a media player entity. The string for the previous command is missing on Crowding and "Zurück" is used for this which is also the translation of the back command.
This leads to confusion in the web configurator as there is no way to distinguish between these commands without searching for the English term.

### How to Reproduce

1. Change language to German
2. Edit an activity
3. Search for the "Zurück" command

### Expected behavior

The back and previous commands should use separate translations

### System version

1.7.7

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Fixed in next release. "Previous" is now "Vorher" in German.
The entity command translations are not yet on Crowdin, they are provided as metadata to the web-configurator.

**Comment by zehnm** [comment]
Part of beta release 1.7.10

**Comment by zehnm** [comment]
Fixed in release 1.7.12
