### ISSUE TITLE
[bug] Mediaplayer image is not scaled properly

### ISSUE THREAD

**Issue by loekf** [unfoldedcircle/bug-reports#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using the Sonos entity via Home Assistent, because the Sonos integration is not working for me (Sonos devices are not detected or loose conmection with the remote after a while).

Looks like whatever icon size you (rows, columns) take, so image is always too large for the icon size.
![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/35070301/78fc9de1-c7d7-435d-a93f-7725eb73e440)

### How to Reproduce

See description

### Expected behavior

The media player picture should always fit inside the icon size, whatever the size.

### System version

1.7.9

### What part of the system affected by the problem?

UI

**Comment by zehnm** [comment]
Probably a duplicate of #350

**Comment by martonborzak** [comment]
Fixed in next release.

**Comment by zehnm** [comment]
Fixed in the just released 1.7.11 beta firmware.

**Comment by kennymc-c** [comment]
Is there any ETA for a new stable firmware with this and all other fixes that are currently only available in beta updates?

**Comment by martonborzak** [comment]
Fixed in 1.7.12.
