### ISSUE TITLE
Clean restore is not really clean

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/bug-reports#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I deleted some uploaded icons from a backup file and then restored it. After reboot the deleted icons where still there.

### How to Reproduce

1. Make backup
2. Delete some Icons from the backup file
3. Restore backup
4. reboot
5. deleted Icons are still there

### Expected behavior

5. deleted Icons are not there anymore

### System version

1.7.10

### What part of the system affected by the problem?

UI

**Comment by zehnm** [comment]
Closing: the backup archive file format is not documented and patching is not supported.
Restore may fail if unsupported files are suddenly included in the archive (like macOS metadata files).
All custom resource files are removed when restoring a backup in non-merge mode.

If you encounter an issue with a regular backup-archive, please open another issue with the core-service logs.
