### ISSUE TITLE
[bug] Top IR emitters do not transmit when "all outputs" is selected

### ISSUE THREAD

**Issue by spl237** [unfoldedcircle/bug-reports#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If "Default (all outputs)" is the selected output port for an IR remote, only the bottom dock emitters are activated; the top emitters are not used. This can be confirmed by using a camera - the one on a mobile phone is fine - to look down into the slot on the top of the dock and transmitting an IR code. If "dock top" is selected, then you can see the top emitters turning on and off when you press a button on the remote; if "all outputs" is selected, they do not turn on. 

### How to Reproduce

1. Select "Default (all outputs)" for an IR remote.
2. Point a camera into the slot on the top of the dock.
3. Press a button on the remote - no IR is emitted from the top emitters

### Expected behavior

IR signals should be visible from the top emitters when a command is sent.

### System version

1.7.12, dock firmware 1.10.0

### What part of the system affected by the problem?

Overall system

**Comment by zehnm** [comment]
Verified the logic and indeed, the top IR is excluded when selecting "All". I'll check if there's any specific reason to do so. If not, this will be fixed in the next release.

**Comment by zehnm** [comment]
Fixed in next release. A beta bugfix release is scheduled for tomorrow, a public release soon afterwards.

This must have been a relict of the early days where parallel IR output in the dock was not yet done in hardware.

**Comment by zehnm** [comment]
Fixed in beta 1.7.13 and I'll close this issue once a public release is out.

**Comment by zehnm** [comment]
Part of 1.7.14
