### ISSUE TITLE
[feature request] Denon AVR Integration - HDMI Output

### ISSUE THREAD

**Issue by loibi** [unfoldedcircle/bug-reports#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Make it possible to switch the HDMI Output. For Instance I have an Marantz Cinema 50 Receiver which works with the Integration. This one has 2 HDMI Outputs which I would like to swicht.
For Instance its possible with Home Assistant.

**Comment by kennymc-c** [comment]
I created a similar request in the denonavr repository: https://github.com/unfoldedcircle/integration-denonavr/issues/37

**Comment by splattner** [comment]
I implemented it in https://github.com/unfoldedcircle/integration-denonavr/pull/39

**Comment by zehnm** [comment]
@loibi this is included in 1.7.14. Could you please test if it works with your receiver?

**Comment by loibi** [comment]
Yes - works Perfect in the current Release. Thank You.
