### ISSUE TITLE
[bug] Old Home Assistant logo on remote

### ISSUE THREAD

**Issue by mvdwetering** [unfoldedcircle/bug-reports#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The remote comes with some icons for Home Automation systems. Home Assistant updated their logo a while back, but the old one is still on the remote

![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/732514/ca748945-a28b-403e-a9f8-7a5b67c0a0d0)

### How to Reproduce

Got resources in settings

### Expected behavior

Current icon shown

### System version

1.7.4

### What part of the system affected by the problem?

UI

**Comment by martonborzak** [comment]
Will be fixed in the next release.

**Comment by zehnm** [comment]
Fixed in 1.8.0 beta release.
