### ISSUE TITLE
[bug] activities provided by integration missing feature 'start'

### ISSUE THREAD

**Issue by Albatross7591** [unfoldedcircle/bug-reports#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Could be related with an other bug: [https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/392](url)

The feature 'start' is missing on a new activity.

### How to Reproduce

1. Create integration
2. During setup integration respond on 'get_available_entities' with one (or more) entities of type 'activity'
3. Select that specific entity
4. Via the restapi search for the added activity; in the response it will show: "features": [],

Workaround: via a request UpdateEntity it is possible to add the feature 'start'.

### Expected behavior

On a new activity the feature 'start' already assigned.

expected: 
"features": [
  "start" 
],

### System version

v1.7.14

### What part of the system affected by the problem?

Core, Integration

**Comment by zehnm** [comment]
See https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/392#issuecomment-2208297643

**Comment by Albatross7591** [comment]
closed: activities should not be made available as entities (see #392)
