### ISSUE TITLE
[bug] Cannot update button mapping to activity (made available by an integration)

### ISSUE THREAD

**Issue by Albatross7591** [unfoldedcircle/bug-reports#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Could be related with an other bug: [https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/392](url)

After selecting activities during integration setup, the integration can not assign a button mapping (error 'Not available')

### How to Reproduce

1. Create integration
2. During setup integration respond on 'get_available_entities' with one (or more) entities of type 'activity'
3. Select that specific entity
4. try to update button mapping (via RESTAPI activities/{activityId}/buttons/{button.Button} ): response will 'Not available'

Workaround for this bug:
Call RESTAPI 'DELETE /activities/{entityId}/buttons' on a new activity will reset button mapping and a new button mapping can be added to the activity

### Expected behavior

Assigning a button mapping to an activity without resetting the button mapping on a new activity

### System version

v1.7.14

### What part of the system affected by the problem?

Core, Integration

**Comment by zehnm** [comment]
See https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/392#issuecomment-2208297643

**Comment by Albatross7591** [comment]
closed: activities should not be made available as entities (see #392)
