### ISSUE TITLE
Wrong time in logfiles (2 hours back from MEZ/Zurich)

### ISSUE THREAD

**Issue by Yezariael75** [unfoldedcircle/bug-reports#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The timestamp in logfiles is 2 hours back from real time (timezone Europe/Zurich). The remote shows for example 23:45 but the timestamp in the logfiles is 21:45.

### How to Reproduce

1. Download logfile
2. compare logfile timestamps to real time

### Expected behavior

Timestamp in logs should be the same as the selected timezone.

### System version

1.1.1

### What part of the system affected by the problem?

Core, Overall system

**Comment by zehnm** [comment]
Not a bug: system logs are in UTC.
See timezone in timestamps, e.g. 
- CSV output: `2023-09-12 11:31:02.024976 +00:00`
- JSON output: `"ts": "2023-09-12T13:21:10.815584+00:00"`
