### ISSUE TITLE
[bug] New Web Configurator Top Bar for editing entities ist missing

### ISSUE THREAD

**Issue by z-master42** [unfoldedcircle/bug-reports#415]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

If I want to edit an existing entity, for example a remote control, the bar for editing the entity is missing. This is only visible once when I create a new entity.
![Image](https://github.com/user-attachments/assets/451838fa-51a1-4646-989e-3fae525333ce)

For activities and macros, however, the bar is permanently visible.

### How to Reproduce

1. Go to Entities at the top
2. Click on an existing entity
3. Notice that you can only change the name and icon for this entity, as the top bar (under the name of the entity with the back arrow) is missing.

### Expected behavior

An entity (in this case remote control) can still be edited after it has been created.

### System version

2.2.0

### What part of the system affected by the problem?

Web Configurator

**Comment by kennymc-c** [comment]
I have this bug with the core simulator. 
But I just found out that when I use the filter function at the top to filter for infrared entities the top bar is shown if you click on one of the entities.
In fact the url is a little different. When using the filter its using /configurator#/remote/ while /configurator#/entity is used without the filter

**Comment by z-master42** [comment]
That's right, that's how it works for me with Bluetooth entities. But if I set the filter to infrared, no entities are displayed at all, even though I have created three remote controls.

For me, the URL ends on entities and does not change when I set a filter. If I change to remotes manually, the page is empty.

**Comment by kennymc-c** [comment]
You need to change the url on the detail page of an entity.

**Comment by z-master42** [comment]
Ahh, that works. Sorry, I had initially misunderstood.

So recognising it as a remote control is wrong? Because on my Bluetooth device, the URL automatically changes to .../remote/...

**Comment by kennymc-c** [comment]
I haven't tested Bluetooth but at least it's not working for infrared and external remotes

**Comment by martonborzak** [comment]
Fixed in 2.2.1.

**Comment by z-master42** [comment]
Hmm, I still have this bug with 2.2.1.

**Comment by kennymc-c** [comment]
Strange as it's fixed for me. Maybe you opened a non remote entity?

**Comment by z-master42** [comment]
No, it's an infrared remote control for my Denon amplifier. However, I still have it so that it is not filtered via the infrared filter. And I have to manually change the entity in the URL to remote to edit it.

**Comment by kennymc-c** [comment]
Have you tried to delete the browser cache?

**Comment by z-master42** [comment]
Ctrl + 5 yes. But it doesn't work on my mobile phone either.

**Comment by z-master42** [comment]
Found a way to fix this permanently:

If I call up the IR remote control and change the path manually from entity to remote and then change an assignment or a button in the settings and then change it back to the original assignment, the remote control is then properly listed as an IR remote and the filter works accordingly.
