### ISSUE TITLE
No further Macros can be created / cloned

### ISSUE THREAD

**Issue by Freshhat** [unfoldedcircle/bug-reports#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently i'm preparing my TV Channels in Macros as it's a sequence of IR commands. But i can't create any additional Macros neither can i clone existing ones.

Is there any hardcoded limitation?

### How to Reproduce

1. Go To Activities & Macros
2. Create 10 Macros
3. Try to create or clone one additional Macro -> will not be saved with that error

Komponentenfehler: m Cannot read properties of undefined (reading 'length')

### Expected behavior

Can create / clone as many macros i want

### System version

1.1.2

### What part of the system affected by the problem?

Web Configurator

### Additional context

![image](https://github.com/unfoldedcircle/bug-reports/assets/18122096/e4e56832-1b2f-44b2-998d-491f2206d304)

**Comment by Freshhat** [comment]
Figured out that this is just a UI related topic. Seems the limit of 10 from the Core-API is hit in the web configurator. If i use the API to get and create the macros it's not a problem. They are simply not displayed.

Can we please adjust the limit in the web config to more than 10? Or maybe page it there

Related API endpoint from the Core is "/api/macros?page=1&limit=100"

**Comment by zehnm** [comment]
The limit in the current version is now 100.

We are aware, that 100 macros might not be enough for everyone. Hopefully it's "good enough" for most use cases until we have proper paging implemented in the web-configurator.
