### ISSUE TITLE
Custom icons are not displayed correctly in the activity web-configurator

### ISSUE THREAD

**Issue by zucki** [unfoldedcircle/bug-reports#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using provided or self-uploaded custom icons for activities, they are not be displayed correctly in the web-configurator

![image](https://github.com/unfoldedcircle/bug-reports/assets/4253035/8ba52f11-ad2a-4b79-b891-d807fa8e204a)

### How to Reproduce

1. Select a icon from "custom icons" for a activity

### Expected behavior

The custom icon is shown in a correct manner like it works for UC icons

### System version

v1.0.3

### What part of the system affected by the problem?

Web Configurator

**Comment by martonborzak** [comment]
Fixed in Release 1.1.0
