### ISSUE TITLE
Backup and restore configuration

### ISSUE THREAD

**Issue by martonborzak** [unfoldedcircle/bug-reports#60]

**Comment by zehnm** [comment]
Currently in testing and planned to be released to BETA group either this or next week.

**Comment by zehnm** [comment]
Part of the BETA group release 1.4.0

**Comment by zehnm** [comment]
Included in 1.4.2
Please note that the web-configurator doesn't show a busy indicator yet during the backup archive creation and restore process! This usually takes a few seconds (worst case: up to around a minute).

We'll also add support articles describing more details about the backup & restore feature.

For now, an extract from the API functions:

### Backup export

- The backup archive is only returned to the client and not stored on the device. 
- It is recommended to perform the backup while the remote is in the docking station.
- Using the remote or the Core-API should be avoided while the backup is running.
- The backup should only take a few seconds. The backup will take longer:
  - if integration drivers are busy and require more time to shutdown.
  - if many custom resources (icons, background images, etc) are present.

⚠️ Attention:
- The backup archive may contain personal information and access keys to external systems.
  - The backup archive is not encrypted. Contained information can be extracted with little effort.
  - For example the long-lived access token for Home Assistant is included, if that integration has been configured.
- All integrations and docks will be disconnected and stopped during backup.
  - They are restarted after the backup is finished. This may take several seconds until all entities are available again.
  - Restart the device, if an integration or entities are no longer working after a backup.
- The device must have enough free disk space to create the backup archive. At least 100 MB must be free to start the backup process.

The backup **does not include**:
- WiFi network configuration and passwords.
- Administrator pin.
- Web-configurator pin.
- Any API-keys created with the Core-API.

### Backup restore

- It is highly recommended to perform the restore while the remote is in the docking station.
- Using the remote or the Core-API should be avoided while the restore is running.
- The restore should only take a few seconds. The restore will take longer:
  - if integration drivers are busy and require more time to shutdown.
  - if many custom resources (icons, background images, etc) are present.

⚠️ Attention:
- The device will not automatically restart after a system restore.
  - The device must be restarted after the restore to activate all changed settings.
  - Certain setting changes like OTA require a system restart.
- WiFi configuration, administrator pin and web-configurator pin are not overwritten by a system restore.
- All integrations and docks will be disconnected and stopped during restore.
- The device must have enough free disk space to restore the backup. At least 100 MB must be free to start the restore process.
