### ISSUE TITLE
IR sequence in activities and macros

### ISSUE THREAD

**Issue by martonborzak** [unfoldedcircle/bug-reports#67]
Add a new remote-entity command to define simple IR code sequences, without having to use macros. Main use case is for switching TV channels and other simple sequences which require multiple key presses.

Example: "DIGIT_1,DIGIT_2,DIGIT_3,CURSOR_ENTER" to change to TV channel 123.

- Sequence consists of IR key names, separated by a comma.
- Only IR keys of the corresponding remote can be used.
- Sequence delay parameter to specify a custom delay between commands.
  This applies the same delay between all keys in the sequence.

**Comment by zehnm** [comment]
Part of the BETA group release 1.4.0

**Comment by zehnm** [comment]
Included in 1.4.2
Please note that the web-configurator only shows a text input field. The IR commands must be separated by a comma `,`.
Example: `DIGIT_1,DIGIT_2,DIGIT_3,CURSOR_ENTER`
An IR command selection is planned for the future.
