### ISSUE TITLE
Media component in activity UI

### ISSUE THREAD

**Issue by martonborzak** [unfoldedcircle/bug-reports#68]
Add a media component to an activity to display artwork and basic media controls on the activity UI for the associated media player entity.

**Comment by zehnm** [comment]
1.4.2 adds support in the Core-API and remote-ui. Web-configurator support is still missing.

**Comment by pvmil** [comment]
Does this also enable to use volume control by a different device?
I use several media-players as supplied by Home Assistant (Logitech media server based), I really like the view and controls in the UI when adding these as a media-player. I cannot control the volume for those who have a separate receiver/amplifier with it's own volume control.

**Comment by kennymc-c** [comment]
@pvmil This is already possible within activities. Just add both devices and map the volume buttons to the volume commands of the amplifier when in the activity ui editor.

This roadmap item here will add the media player ui (that you see when you open the integration directly and not through the activity) as a ui component in the activity ui editor (like the text and icon components).

**Comment by zehnm** [comment]
The next release will have web-configurator support for a media-player UI component:

<img width="799" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/ebbfa494-9b2a-4575-b812-06942b2d607a">

**Comment by pvmil** [comment]
> @pvmil This is already possible within activities. Just add both devices and map the volume buttons to the volume commands of the amplifier when in the activity ui editor.
> 
> This roadmap item here will add the media player ui (that you see when you open the integration directly and not through the activity) as a ui component in the activity ui editor (like the text and icon components).

Kennymc-c / Zehnm, that's indeed what I miss, adding media in the UI. Thanks for great effort

**Comment by zehnm** [comment]
Closing: part of 1.4.3
