### ISSUE TITLE
Creating/Editing groups does not provide a "save"-button

### ISSUE THREAD

**Issue by Talkabout** [unfoldedcircle/bug-reports#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating or editing a group there are buttons for "select all entities" and "add entity to group", but there is no button to save the group. The only way to do so (I have found) is to focus the label field and hit the "enter" button.

### How to Reproduce

1. Go to profile page
2. select profile
3. go to "Groups"
4. hit "create group"
5. select label and entities for group
6. save group (no button)

### Expected behavior

There should be a "save" button for groups

### What part of the system affected by the problem?

Web Configurator

**Comment by martonborzak** [comment]
Fixed in Release 1.1.0
