### ISSUE TITLE
Set brightness not working in macros

### ISSUE THREAD

**Issue by Laess3r** [unfoldedcircle/bug-reports#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating a new macro to dim one or multiple lights, the brightness value is not stored.
When returning to the page it is always shown as "0%" and the macro is not working.

![image](https://github.com/unfoldedcircle/bug-reports/assets/3459599/ab94d1b3-b422-416f-9d78-445ada6acd30)

### How to Reproduce

1. Go to "Activities and Macros"
2. Edit a Macro
3. Add "set brightness" command of any light entity (i am using lights from home assistant which work fine when added as entity to the UI)
4. Set any brightness value
5. save / leave the page
6. Come back --> 0% is shown

### Expected behavior

I expect the set brightness to work.

### System version

v1.0.3

### What part of the system affected by the problem?

Web Configurator

**Comment by martonborzak** [comment]
Fixed in Release 1.1.0
