### ISSUE TITLE
[bug] Built-in IR data for Microsoft MCE remotes raises errors

### ISSUE THREAD

**Issue by wawa79** [unfoldedcircle/bug-reports#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sending IR codes from the built-on "Microsoft MCE remote (standard)",  "Microsoft MCE remote (keyboard)" and others MCE raise error: "Bad request" errors.
Adding custom IR buttons or editing the IR code raises error: "Component Error: 5 Cannot read properties of undefined (reading '0')"

### How to Reproduce

Go to Remotes
Add the MCE remote  from the provided IR dataset (Manufacturer=Microsoft, device=MCE...
Go to key CURSOR_UP and try triggering the IR > error "Bad request"
Edit the key CURSOR_UP and set a new IR code >  error "Component Error: 5 Cannot read properties of undefined (reading '0'"

### Expected behavior

IR codes to be sent / proessed

### System version

1.2.1

### What part of the system affected by the problem?

Core

### Additional context
Adding Pronto code in case the length might be an issue (I hardly but successfully added pronto custom codes for other devices);
0001 0073 0000 0022 0060 0020 0010 0010 0010 0010 0010 0020 0010 0020 0030 0020 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0020 0010 0010 0010 0010 0010 0010 0010 0010 0020 0010 0010 0010 0010 0010 0010 0020 0020 0010 0010 0010 0010 0010 0010 0010 0010 0020 0010 0010 0010 0010 0010 0010 0020 0010 09AC

_No response_

**Comment by zehnm** [comment]
I've checked the MCE codes and this seems to be the same issue as #26: 
Most of the MCE IR codes consist of 2 IR commands. We're working on fix.

**Comment by zehnm** [comment]
Part of the BETA group release 1.4.0 and included in next public release.

**Comment by wawa79** [comment]
I'll give it a try this wek-end. Thanks

**Comment by zehnm** [comment]
Fixed in 1.4.2
