### ISSUE TITLE
Information about set token wrong

### ISSUE THREAD

**Issue by Talkabout** [unfoldedcircle/bug-reports#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Integration driver UI always says "Token not set":

![image](https://github.com/unfoldedcircle/bug-reports/assets/10157917/02c669a0-8eb1-4b55-84a1-5b2067243c38)

Even though a token is set.

### How to Reproduce

1. add custom integration
2. set url and token
3. check integration settings page

### Expected behavior

"Token set" should be visible.

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment]
Quick fix in next version: misleading label is removed.
Per API definition, the token is never exposed and can only be set, but not read out again. Displaying an indicator in the UI if a token is set or not, will require an API change.

**Comment by zehnm** [comment]
Closing: label is no longer shown in current version
