### ISSUE TITLE
[feature request] Support numbers / numpad on media_player entity

### ISSUE THREAD

**Issue by splattner** [unfoldedcircle/bug-reports#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The [media_player entity](https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_media_player.md) only supports the `dpad` feature. I suggest also support something like a `numpad` feature to allow input for 0 - 9 numbers like often seen on a tv remote.

**Comment by zehnm** [comment]
The media-player entity now supports many new features plus "simple commands" for any commands not included in a feature. This can already be used for custom integrations. Included integrations like Android TV will support it in the next release (already released as 1.7.9 beta).

More information:
- https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_media_player.md
- https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/command_mapping.md
