### ISSUE TITLE
[bug] Hue - Request timed out / uc_hue_driver session not available

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every now and then I get a request timed out / uc_hue_driver session not available error on the remote when turning hue entities on or off. Sometimes the commands are executed delayed or not at all. This happens with various lights but as far as I tried just when turning them on or off but not when changing brightness, color temperature or color. I have attached the debug logs for the core, remote ui and hue integration.

[UCR2_logs_2023-10-01.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/12777888/UCR2_logs_2023-10-01.txt)

### How to Reproduce

1. Turn Hue light on or off
2. Wait for the error to appear on the remote
3. Command was not executed or gets executed delayed

### Expected behavior

Request should not time out and the commands should be executed without a delay

### System version

1.3.3

### What part of the system affected by the problem?

Integration

**Comment by zehnm** [comment]
Fixed the error `Invalid JSON message: invalid type: boolean 'true', expected u16` shown in the log in 1.4.2.
This lead to UI timeout errors and integration disconnects.
